analysis:
  stage: analysis
  image: ${TEST_IMAGE}
  before_script:
    - touch cppcheck_log.txt
  script:
    - cppcheck  src/*  --enable=all --language=c++ --suppress=missingIncludeSystem --error-exitcode=1 --output-file=cppcheck_log.txt
  after_script:
    - cat cppcheck_log.txt
  artifacts:
    reports:
    paths:
      - cppcheck_log.txt
  rules:
      - allow_failure: true 
