/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_formats_c3dt_GLTF */

#ifndef _Included_com_atakmap_map_formats_c3dt_GLTF
#define _Included_com_atakmap_map_formats_c3dt_GLTF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_formats_c3dt_GLTF
 * Method:    createFromFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_formats_c3dt_GLTF_createFromFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_atakmap_map_formats_c3dt_GLTF
 * Method:    createFromBytes
 * Signature: ([BIILjava/lang/String;Lcom/atakmap/map/formats/c3dt/ContentSource;)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_formats_c3dt_GLTF_createFromBytes
  (JNIEnv *, jclass, jbyteArray, jint, jint, jstring, jobject);

/*
 * Class:     com_atakmap_map_formats_c3dt_GLTF
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_formats_c3dt_GLTF_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_formats_c3dt_GLTF
 * Method:    draw
 * Signature: (JZI[D)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_formats_c3dt_GLTF_draw
  (JNIEnv *, jclass, jlong, jboolean, jint, jdoubleArray);

/*
 * Class:     com_atakmap_map_formats_c3dt_GLTF
 * Method:    bindModel
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_formats_c3dt_GLTF_bindModel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_formats_c3dt_GLTF
 * Method:    releaseModel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_formats_c3dt_GLTF_releaseModel
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
