/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_util_ConfigOptions */

#ifndef _Included_com_atakmap_util_ConfigOptions
#define _Included_com_atakmap_util_ConfigOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_util_ConfigOptions
 * Method:    setOption
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_util_ConfigOptions_setOption
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_atakmap_util_ConfigOptions
 * Method:    getOption
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_util_ConfigOptions_getOption
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
