/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_interop_DataType */

#ifndef _Included_com_atakmap_interop_DataType
#define _Included_com_atakmap_interop_DataType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_interop_DataType
 * Method:    getTEDT_UInt8
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_interop_DataType_getTEDT_1UInt8
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_interop_DataType
 * Method:    getTEDT_Int8
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_interop_DataType_getTEDT_1Int8
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_interop_DataType
 * Method:    getTEDT_UInt16
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_interop_DataType_getTEDT_1UInt16
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_interop_DataType
 * Method:    getTEDT_Int16
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_interop_DataType_getTEDT_1Int16
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_interop_DataType
 * Method:    getTEDT_UInt32
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_interop_DataType_getTEDT_1UInt32
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_interop_DataType
 * Method:    getTEDT_Int32
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_interop_DataType_getTEDT_1Int32
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_interop_DataType
 * Method:    getTEDT_Float32
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_interop_DataType_getTEDT_1Float32
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_interop_DataType
 * Method:    getTEDT_Float64
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_interop_DataType_getTEDT_1Float64
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
