/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_database_impl_DatabaseImpl */

#ifndef _Included_com_atakmap_database_impl_DatabaseImpl
#define _Included_com_atakmap_database_impl_DatabaseImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef com_atakmap_database_impl_DatabaseImpl_OPEN_READONLY
#define com_atakmap_database_impl_DatabaseImpl_OPEN_READONLY 1L
#undef com_atakmap_database_impl_DatabaseImpl_OPEN_CREATE
#define com_atakmap_database_impl_DatabaseImpl_OPEN_CREATE 2L
/*
 * Class:     com_atakmap_database_impl_DatabaseImpl
 * Method:    openImpl
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_database_impl_DatabaseImpl_openImpl
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_atakmap_database_impl_DatabaseImpl
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_database_impl_DatabaseImpl_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_database_impl_DatabaseImpl
 * Method:    compileStatement
 * Signature: (JLjava/lang/String;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_database_impl_DatabaseImpl_compileStatement
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_atakmap_database_impl_DatabaseImpl
 * Method:    compileQuery
 * Signature: (JLjava/lang/String;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_database_impl_DatabaseImpl_compileQuery
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_atakmap_database_impl_DatabaseImpl
 * Method:    isReadOnly
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_database_impl_DatabaseImpl_isReadOnly
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_database_impl_DatabaseImpl
 * Method:    getVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_database_impl_DatabaseImpl_getVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_database_impl_DatabaseImpl
 * Method:    setVersion
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_database_impl_DatabaseImpl_setVersion
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_atakmap_database_impl_DatabaseImpl
 * Method:    beginTransaction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_database_impl_DatabaseImpl_beginTransaction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_database_impl_DatabaseImpl
 * Method:    setTransactionSuccessful
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_database_impl_DatabaseImpl_setTransactionSuccessful
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_database_impl_DatabaseImpl
 * Method:    endTransaction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_database_impl_DatabaseImpl_endTransaction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_database_impl_DatabaseImpl
 * Method:    inTransaction
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_database_impl_DatabaseImpl_inTransaction
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
