/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_raster_drg_DRGInfo */

#ifndef _Included_com_atakmap_map_layer_raster_drg_DRGInfo
#define _Included_com_atakmap_map_layer_raster_drg_DRGInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_raster_drg_DRGInfo
 * Method:    parse
 * Signature: (Ljava/lang/String;[D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_raster_drg_DRGInfo_parse
  (JNIEnv *, jclass, jstring, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
