/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_coremap_maps_conversion_EGM96 */

#ifndef _Included_com_atakmap_coremap_maps_conversion_EGM96
#define _Included_com_atakmap_coremap_maps_conversion_EGM96
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_coremap_maps_conversion_EGM96
 * Method:    getOffset
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_coremap_maps_conversion_EGM96_getOffset
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
