/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_elevation_ElevationManager */

#ifndef _Included_com_atakmap_map_elevation_ElevationManager
#define _Included_com_atakmap_map_elevation_ElevationManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_elevation_ElevationManager
 * Method:    getGeoidHeight
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_elevation_ElevationManager_getGeoidHeight
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_atakmap_map_elevation_ElevationManager
 * Method:    queryElevationSources
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_elevation_ElevationManager_queryElevationSources
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_ElevationManager
 * Method:    queryElevationSourcesCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_elevation_ElevationManager_queryElevationSourcesCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_ElevationManager
 * Method:    getElevation
 * Signature: (DDJ[Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_elevation_ElevationManager_getElevation__DDJ_3Ljava_lang_String_2
  (JNIEnv *, jclass, jdouble, jdouble, jlong, jobjectArray);

/*
 * Class:     com_atakmap_map_elevation_ElevationManager
 * Method:    getElevation
 * Signature: ([DIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_elevation_ElevationManager_getElevation___3DIJ
  (JNIEnv *, jclass, jdoubleArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_elevation_ElevationManager_ElevationModelFilter */

#ifndef _Included_com_atakmap_map_elevation_ElevationManager_ElevationModelFilter
#define _Included_com_atakmap_map_elevation_ElevationManager_ElevationModelFilter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_elevation_ElevationManager_QueryParameters */

#ifndef _Included_com_atakmap_map_elevation_ElevationManager_QueryParameters
#define _Included_com_atakmap_map_elevation_ElevationManager_QueryParameters
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
