/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_elevation_ElevationSourceManager */

#ifndef _Included_com_atakmap_map_elevation_ElevationSourceManager
#define _Included_com_atakmap_map_elevation_ElevationSourceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_elevation_ElevationSourceManager
 * Method:    addOnSourcesChangedListener
 * Signature: (Lcom/atakmap/map/elevation/ElevationSourceManager/OnSourcesChangedListener;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_elevation_ElevationSourceManager_addOnSourcesChangedListener
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_elevation_ElevationSourceManager
 * Method:    removeOnSourcesChangedListener
 * Signature: (Lcom/atakmap/map/elevation/ElevationSourceManager/OnSourcesChangedListener;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_elevation_ElevationSourceManager_removeOnSourcesChangedListener
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_elevation_ElevationSourceManager
 * Method:    attach
 * Signature: (Lcom/atakmap/map/elevation/ElevationSource;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_elevation_ElevationSourceManager_attach
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_elevation_ElevationSourceManager
 * Method:    detach
 * Signature: (Lcom/atakmap/map/elevation/ElevationSource;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_elevation_ElevationSourceManager_detach
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_elevation_ElevationSourceManager
 * Method:    findSource
 * Signature: (Ljava/lang/String;)Lcom/atakmap/map/elevation/ElevationSource;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_elevation_ElevationSourceManager_findSource
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_atakmap_map_elevation_ElevationSourceManager
 * Method:    getSources
 * Signature: (Ljava/util/Collection;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_elevation_ElevationSourceManager_getSources
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_elevation_ElevationSourceManager_OnSourcesChangedListener */

#ifndef _Included_com_atakmap_map_elevation_ElevationSourceManager_OnSourcesChangedListener
#define _Included_com_atakmap_map_elevation_ElevationSourceManager_OnSourcesChangedListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
