/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_feature_Feature */

#ifndef _Included_com_atakmap_map_layer_feature_Feature
#define _Included_com_atakmap_map_layer_feature_Feature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_feature_Feature
 * Method:    create
 * Signature: (JJLjava/lang/String;JIDJJJJ)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_Feature_create
  (JNIEnv *, jclass, jlong, jlong, jstring, jlong, jint, jdouble, jlong, jlong, jlong, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_Feature
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_Feature_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_Feature
 * Method:    getFeatureSetId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_Feature_getFeatureSetId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_Feature
 * Method:    getId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_Feature_getId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_Feature
 * Method:    getVersion
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_Feature_getVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_Feature
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_layer_feature_Feature_getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_Feature
 * Method:    getGeometry
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_Feature_getGeometry
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_Feature
 * Method:    getStyle
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_Feature_getStyle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_Feature
 * Method:    getAttributes
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_Feature_getAttributes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_Feature
 * Method:    getTimestamp
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_Feature_getTimestamp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_Feature
 * Method:    getAltitudeMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_Feature_getAltitudeMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_Feature
 * Method:    getExtrude
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_layer_feature_Feature_getExtrude
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_feature_Feature_AltitudeMode */

#ifndef _Included_com_atakmap_map_layer_feature_Feature_AltitudeMode
#define _Included_com_atakmap_map_layer_feature_Feature_AltitudeMode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
