/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_math_Frustum */

#ifndef _Included_com_atakmap_math_Frustum
#define _Included_com_atakmap_math_Frustum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_math_Frustum
 * Method:    create
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_math_Frustum_create
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_Frustum
 * Method:    intersectsSphere
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_math_Frustum_intersectsSphere
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_math_Frustum
 * Method:    intersectsAABB
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_math_Frustum_intersectsAABB
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_math_Frustum
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Frustum_destruct
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
