/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_gdal_GdalLibrary */

#ifndef _Included_com_atakmap_map_gdal_GdalLibrary
#define _Included_com_atakmap_map_gdal_GdalLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_gdal_GdalLibrary
 * Method:    registerProjectionSpi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_gdal_GdalLibrary_registerProjectionSpi
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_gdal_GdalLibrary_DatabaseInfo */

#ifndef _Included_com_atakmap_map_gdal_GdalLibrary_DatabaseInfo
#define _Included_com_atakmap_map_gdal_GdalLibrary_DatabaseInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
