/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_coremap_maps_coords_GeoCalculations */

#ifndef _Included_com_atakmap_coremap_maps_coords_GeoCalculations
#define _Included_com_atakmap_coremap_maps_coords_GeoCalculations
#ifdef __cplusplus
extern "C" {
#endif
#undef com_atakmap_coremap_maps_coords_GeoCalculations_HEMISPHERE_EAST
#define com_atakmap_coremap_maps_coords_GeoCalculations_HEMISPHERE_EAST 0L
#undef com_atakmap_coremap_maps_coords_GeoCalculations_HEMISPHERE_WEST
#define com_atakmap_coremap_maps_coords_GeoCalculations_HEMISPHERE_WEST 1L
#undef com_atakmap_coremap_maps_coords_GeoCalculations_CALC_SLANT
#define com_atakmap_coremap_maps_coords_GeoCalculations_CALC_SLANT 2L
#undef com_atakmap_coremap_maps_coords_GeoCalculations_CALC_QUICK
#define com_atakmap_coremap_maps_coords_GeoCalculations_CALC_QUICK 1L
/*
 * Class:     com_atakmap_coremap_maps_coords_GeoCalculations
 * Method:    distance
 * Signature: (DDDDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_coremap_maps_coords_GeoCalculations_distance
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     com_atakmap_coremap_maps_coords_GeoCalculations
 * Method:    slantAngle
 * Signature: (DDDDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_coremap_maps_coords_GeoCalculations_slantAngle
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     com_atakmap_coremap_maps_coords_GeoCalculations
 * Method:    bearing
 * Signature: (DDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_coremap_maps_coords_GeoCalculations_bearing
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     com_atakmap_coremap_maps_coords_GeoCalculations
 * Method:    midpoint
 * Signature: (DDDDDDI)Lcom/atakmap/coremap/maps/coords/GeoPoint;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_coremap_maps_coords_GeoCalculations_midpoint
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     com_atakmap_coremap_maps_coords_GeoCalculations
 * Method:    pointAtDistance
 * Signature: (DDDDI)Lcom/atakmap/coremap/maps/coords/GeoPoint;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_coremap_maps_coords_GeoCalculations_pointAtDistance
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
