/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_feature_geometry_GeometryFactory */

#ifndef _Included_com_atakmap_map_layer_feature_geometry_GeometryFactory
#define _Included_com_atakmap_map_layer_feature_geometry_GeometryFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    computeSpatiaLiteBlobSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_computeSpatiaLiteBlobSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    toSpatiaLiteBlob
 * Signature: (JI[BIIZ)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_toSpatiaLiteBlob__JI_3BIIZ
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jint, jint, jboolean);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    toSpatiaLiteBlob
 * Signature: (JIJIZ)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_toSpatiaLiteBlob__JIJIZ
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jboolean);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    parseSpatiaLiteBlob
 * Signature: ([BII[I[I)Lcom/atakmap/map/layer/feature/geometry/Geometry;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_parseSpatiaLiteBlob___3BII_3I_3I
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray, jintArray);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    parseSpatiaLiteBlob
 * Signature: (JI[I[I)Lcom/atakmap/map/layer/feature/geometry/Geometry;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_parseSpatiaLiteBlob__JI_3I_3I
  (JNIEnv *, jclass, jlong, jint, jintArray, jintArray);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    computeWkbSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_computeWkbSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    toWkb
 * Signature: (J[BIIZ)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_toWkb__J_3BIIZ
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jboolean);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    toWkb
 * Signature: (JJIZ)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_toWkb__JJIZ
  (JNIEnv *, jclass, jlong, jlong, jint, jboolean);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    parseWkb
 * Signature: ([BII[I)Lcom/atakmap/map/layer/feature/geometry/Geometry;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_parseWkb___3BII_3I
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    parseWkb
 * Signature: (JI[I)Lcom/atakmap/map/layer/feature/geometry/Geometry;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_parseWkb__JI_3I
  (JNIEnv *, jclass, jlong, jint, jintArray);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    createEllipse
 * Signature: (JDDDI)Lcom/atakmap/map/layer/feature/geometry/Geometry;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_createEllipse__JDDDI
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jint);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    createEllipse
 * Signature: (DDDDI)Lcom/atakmap/map/layer/feature/geometry/Geometry;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_createEllipse__DDDDI
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    extrudeConstant
 * Signature: (JDI)Lcom/atakmap/map/layer/feature/geometry/Geometry;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_extrudeConstant
  (JNIEnv *, jclass, jlong, jdouble, jint);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    extrudePerVertex
 * Signature: (J[DI)Lcom/atakmap/map/layer/feature/geometry/Geometry;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_extrudePerVertex
  (JNIEnv *, jclass, jlong, jdoubleArray, jint);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    createRectangle
 * Signature: (JJI)Lcom/atakmap/map/layer/feature/geometry/Geometry;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_createRectangle__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    createRectangle
 * Signature: (JJJI)Lcom/atakmap/map/layer/feature/geometry/Geometry;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_createRectangle__JJJI
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_GeometryFactory
 * Method:    createRectangle
 * Signature: (JDDDI)Lcom/atakmap/map/layer/feature/geometry/Geometry;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_GeometryFactory_createRectangle__JDDDI
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_feature_geometry_GeometryFactory_ExtrusionHints */

#ifndef _Included_com_atakmap_map_layer_feature_geometry_GeometryFactory_ExtrusionHints
#define _Included_com_atakmap_map_layer_feature_geometry_GeometryFactory_ExtrusionHints
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_feature_geometry_GeometryFactory_Algorithm */

#ifndef _Included_com_atakmap_map_layer_feature_geometry_GeometryFactory_Algorithm
#define _Included_com_atakmap_map_layer_feature_geometry_GeometryFactory_Algorithm
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
