/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_coremap_maps_conversion_GeomagneticField */

#ifndef _Included_com_atakmap_coremap_maps_conversion_GeomagneticField
#define _Included_com_atakmap_coremap_maps_conversion_GeomagneticField
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_coremap_maps_conversion_GeomagneticField
 * Method:    getDeclination
 * Signature: (DDDIII)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_coremap_maps_conversion_GeomagneticField_getDeclination
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jint, jint, jint);

/*
 * Class:     com_atakmap_coremap_maps_conversion_GeomagneticField
 * Method:    getFieldStrength
 * Signature: (DDDIII)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_coremap_maps_conversion_GeomagneticField_getFieldStrength
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jint, jint, jint);

/*
 * Class:     com_atakmap_coremap_maps_conversion_GeomagneticField
 * Method:    getHorizontalStrength
 * Signature: (DDDIII)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_coremap_maps_conversion_GeomagneticField_getHorizontalStrength
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jint, jint, jint);

/*
 * Class:     com_atakmap_coremap_maps_conversion_GeomagneticField
 * Method:    getInclination
 * Signature: (DDDIII)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_coremap_maps_conversion_GeomagneticField_getInclination
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jint, jint, jint);

/*
 * Class:     com_atakmap_coremap_maps_conversion_GeomagneticField
 * Method:    getX
 * Signature: (DDDIII)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_coremap_maps_conversion_GeomagneticField_getX
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jint, jint, jint);

/*
 * Class:     com_atakmap_coremap_maps_conversion_GeomagneticField
 * Method:    getY
 * Signature: (DDDIII)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_coremap_maps_conversion_GeomagneticField_getY
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jint, jint, jint);

/*
 * Class:     com_atakmap_coremap_maps_conversion_GeomagneticField
 * Method:    getZ
 * Signature: (DDDIII)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_coremap_maps_conversion_GeomagneticField_getZ
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
