/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_feature_geometry_Geometry */

#ifndef _Included_com_atakmap_map_layer_feature_geometry_Geometry
#define _Included_com_atakmap_map_layer_feature_geometry_Geometry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    clone
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_clone
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    getTEGC_Point
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_getTEGC_1Point
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    getTEGC_LineString
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_getTEGC_1LineString
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    getTEGC_Polygon
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_getTEGC_1Polygon
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    getTEGC_GeometryCollection
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_getTEGC_1GeometryCollection
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    equals
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_equals
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    destroy
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_destroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    getEnvelope
 * Signature: (Lcom/atakmap/interop/Pointer;[D)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_getEnvelope
  (JNIEnv *, jclass, jobject, jdoubleArray);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    getDimension
 * Signature: (Lcom/atakmap/interop/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_getDimension
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    setDimension
 * Signature: (Lcom/atakmap/interop/Pointer;I)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_setDimension
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    getGeometryClass
 * Signature: (Lcom/atakmap/interop/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_getGeometryClass
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Point_create
 * Signature: (DD)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Point_1create__DD
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Point_create
 * Signature: (DDD)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Point_1create__DDD
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Point_getX
 * Signature: (Lcom/atakmap/interop/Pointer;)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Point_1getX
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Point_getY
 * Signature: (Lcom/atakmap/interop/Pointer;)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Point_1getY
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Point_getZ
 * Signature: (Lcom/atakmap/interop/Pointer;)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Point_1getZ
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Point_set
 * Signature: (Lcom/atakmap/interop/Pointer;DD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Point_1set__Lcom_atakmap_interop_Pointer_2DD
  (JNIEnv *, jclass, jobject, jdouble, jdouble);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Point_set
 * Signature: (Lcom/atakmap/interop/Pointer;DDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Point_1set__Lcom_atakmap_interop_Pointer_2DDD
  (JNIEnv *, jclass, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Linestring_create
 * Signature: (I)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Linestring_1create
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Linestring_getNumPoints
 * Signature: (Lcom/atakmap/interop/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Linestring_1getNumPoints
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Linestring_isClosed
 * Signature: (Lcom/atakmap/interop/Pointer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Linestring_1isClosed
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Linestring_getX
 * Signature: (Lcom/atakmap/interop/Pointer;I)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Linestring_1getX
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Linestring_getY
 * Signature: (Lcom/atakmap/interop/Pointer;I)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Linestring_1getY
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Linestring_getZ
 * Signature: (Lcom/atakmap/interop/Pointer;I)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Linestring_1getZ
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Linestring_addPoint
 * Signature: (Lcom/atakmap/interop/Pointer;DD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Linestring_1addPoint__Lcom_atakmap_interop_Pointer_2DD
  (JNIEnv *, jclass, jobject, jdouble, jdouble);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Linestring_addPoint
 * Signature: (Lcom/atakmap/interop/Pointer;DDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Linestring_1addPoint__Lcom_atakmap_interop_Pointer_2DDD
  (JNIEnv *, jclass, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Linestring_addPoints
 * Signature: (Lcom/atakmap/interop/Pointer;[DIII)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Linestring_1addPoints
  (JNIEnv *, jclass, jobject, jdoubleArray, jint, jint, jint);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Linestring_setX
 * Signature: (Lcom/atakmap/interop/Pointer;ID)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Linestring_1setX
  (JNIEnv *, jclass, jobject, jint, jdouble);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Linestring_setY
 * Signature: (Lcom/atakmap/interop/Pointer;ID)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Linestring_1setY
  (JNIEnv *, jclass, jobject, jint, jdouble);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Linestring_setZ
 * Signature: (Lcom/atakmap/interop/Pointer;ID)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Linestring_1setZ
  (JNIEnv *, jclass, jobject, jint, jdouble);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Polygon_create
 * Signature: (I)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Polygon_1create
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Polygon_setExteriorRing
 * Signature: (Lcom/atakmap/interop/Pointer;Lcom/atakmap/interop/Pointer;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Polygon_1setExteriorRing
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Polygon_addInteriorRing
 * Signature: (Lcom/atakmap/interop/Pointer;Lcom/atakmap/interop/Pointer;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Polygon_1addInteriorRing
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Polygon_removeInteriorRing
 * Signature: (Lcom/atakmap/interop/Pointer;Lcom/atakmap/interop/Pointer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Polygon_1removeInteriorRing
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Polygon_containsInteriorRing
 * Signature: (Lcom/atakmap/map/layer/feature/geometry/Polygon;Lcom/atakmap/interop/Pointer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Polygon_1containsInteriorRing
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Polygon_clear
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Polygon_1clear
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Polygon_clearInteriorRings
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Polygon_1clearInteriorRings
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Polygon_getExteriorRing
 * Signature: (Lcom/atakmap/interop/Pointer;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Polygon_1getExteriorRing
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Polygon_getNumInteriorRings
 * Signature: (Lcom/atakmap/interop/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Polygon_1getNumInteriorRings
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    Polygon_getInteriorRing
 * Signature: (Lcom/atakmap/interop/Pointer;I)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_Polygon_1getInteriorRing
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    GeometryCollection_create
 * Signature: (I)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_GeometryCollection_1create
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    GeometryCollection_add
 * Signature: (Lcom/atakmap/interop/Pointer;Lcom/atakmap/interop/Pointer;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_GeometryCollection_1add
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    GeometryCollection_remove
 * Signature: (Lcom/atakmap/interop/Pointer;Lcom/atakmap/interop/Pointer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_GeometryCollection_1remove
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    GeometryCollection_getNumChildren
 * Signature: (Lcom/atakmap/interop/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_GeometryCollection_1getNumChildren
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    GeometryCollection_getChild
 * Signature: (Lcom/atakmap/interop/Pointer;I)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_GeometryCollection_1getChild
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_atakmap_map_layer_feature_geometry_Geometry
 * Method:    GeometryCollection_clear
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_geometry_Geometry_GeometryCollection_1clear
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
