/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_opengl_GLLineBatch */

#ifndef _Included_com_atakmap_opengl_GLLineBatch
#define _Included_com_atakmap_opengl_GLLineBatch
#ifdef __cplusplus
extern "C" {
#endif
#undef com_atakmap_opengl_GLLineBatch_LINES_VERTEX_SIZE
#define com_atakmap_opengl_GLLineBatch_LINES_VERTEX_SIZE 12L
/*
 * Class:     com_atakmap_opengl_GLLineBatch
 * Method:    addLineNative
 * Signature: (Ljava/nio/ByteBuffer;IIFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLLineBatch_addLineNative
  (JNIEnv *, jobject, jobject, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_atakmap_opengl_GLLineBatch
 * Method:    addLinesNative
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/FloatBuffer;IIFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLLineBatch_addLinesNative
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jint, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_atakmap_opengl_GLLineBatch
 * Method:    addLinestripNative
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/FloatBuffer;IIFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLLineBatch_addLinestripNative
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jint, jint, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
