/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_opengl_GLLayerFactory */

#ifndef _Included_com_atakmap_map_layer_opengl_GLLayerFactory
#define _Included_com_atakmap_map_layer_opengl_GLLayerFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_opengl_GLLayerFactory
 * Method:    register
 * Signature: (Lcom/atakmap/interop/Pointer;I)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_opengl_GLLayerFactory_register
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_atakmap_map_layer_opengl_GLLayerFactory
 * Method:    unregister
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_opengl_GLLayerFactory_unregister
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_opengl_GLLayerFactory
 * Method:    create
 * Signature: (JJ)Lcom/atakmap/map/layer/opengl/GLLayer2;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_opengl_GLLayerFactory_create
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_map_layer_opengl_GLLayerFactory
 * Method:    adaptJavaToLayer2
 * Signature: (Lcom/atakmap/interop/Pointer;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_opengl_GLLayerFactory_adaptJavaToLayer2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_opengl_GLLayerFactory
 * Method:    adaptNativeToLayer2
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_opengl_GLLayerFactory_adaptNativeToLayer2
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_opengl_GLLayerFactory
 * Method:    destructLayer2
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_opengl_GLLayerFactory_destructLayer2
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_opengl_GLLayerFactory_ResolvableAdapter */

#ifndef _Included_com_atakmap_map_layer_opengl_GLLayerFactory_ResolvableAdapter
#define _Included_com_atakmap_map_layer_opengl_GLLayerFactory_ResolvableAdapter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_opengl_GLLayerFactory_Adapter */

#ifndef _Included_com_atakmap_map_layer_opengl_GLLayerFactory_Adapter
#define _Included_com_atakmap_map_layer_opengl_GLLayerFactory_Adapter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
