/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_opengl_GLNinePatch */

#ifndef _Included_com_atakmap_opengl_GLNinePatch
#define _Included_com_atakmap_opengl_GLNinePatch
#ifdef __cplusplus
extern "C" {
#endif
#undef com_atakmap_opengl_GLNinePatch_NUM_VERTS_PER_CORNER
#define com_atakmap_opengl_GLNinePatch_NUM_VERTS_PER_CORNER 8L
#undef com_atakmap_opengl_GLNinePatch_NUM_VERTS_PER_PATCH
#define com_atakmap_opengl_GLNinePatch_NUM_VERTS_PER_PATCH 33L
#undef com_atakmap_opengl_GLNinePatch_RADIANS_PER_VERT
#define com_atakmap_opengl_GLNinePatch_RADIANS_PER_VERT 0.19634954084936207
/*
 * Class:     com_atakmap_opengl_GLNinePatch
 * Method:    buildPatchVerts
 * Signature: (Ljava/nio/FloatBuffer;IFDFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLNinePatch_buildPatchVerts
  (JNIEnv *, jclass, jobject, jint, jfloat, jdouble, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_atakmap_opengl_GLNinePatch
 * Method:    buildPatchVerts3d
 * Signature: (Ljava/nio/FloatBuffer;IFDFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLNinePatch_buildPatchVerts3d
  (JNIEnv *, jclass, jobject, jint, jfloat, jdouble, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_atakmap_opengl_GLNinePatch
 * Method:    fillCoordsBuffer
 * Signature: (FFFFFFFFLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLNinePatch_fillCoordsBuffer
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jobject);

/*
 * Class:     com_atakmap_opengl_GLNinePatch
 * Method:    fillCoordsBuffer3d
 * Signature: (FFFFFFFFFLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLNinePatch_fillCoordsBuffer3d
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jobject);

#ifdef __cplusplus
}
#endif
#endif
