/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2 */

#ifndef _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2
#define _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2
#ifdef __cplusplus
extern "C" {
#endif
#undef com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_DEBUG
#define com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_DEBUG 0L
#undef com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_TEXTURE_CACHE_HINT_RESOLVED
#define com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_TEXTURE_CACHE_HINT_RESOLVED 1L
/*
 * Class:     com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2
 * Method:    setLCS
 * Signature: (JIDDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_setLCS
  (JNIEnv *, jclass, jlong, jint, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_Initializer */

#ifndef _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_Initializer
#define _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_Initializer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_Initializer_Result */

#ifndef _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_Initializer_Result
#define _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_Initializer_Result
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_NodeCore */

#ifndef _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_NodeCore
#define _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_NodeCore
#ifdef __cplusplus
extern "C" {
#endif
#undef com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_NodeCore_POLE_LATITUDE_LIMIT_EPISLON
#define com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_NodeCore_POLE_LATITUDE_LIMIT_EPISLON 1.0E-5
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_Options */

#ifndef _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_Options
#define _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_Options
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_PreciseVertexResolver */

#ifndef _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_PreciseVertexResolver
#define _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_PreciseVertexResolver
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_DefaultVertexResolver */

#ifndef _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_DefaultVertexResolver
#define _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_DefaultVertexResolver
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_VertexResolver */

#ifndef _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_VertexResolver
#define _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_VertexResolver
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_GridVertex */

#ifndef _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_GridVertex
#define _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_GridVertex
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_VertexCoordInfo */

#ifndef _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_VertexCoordInfo
#define _Included_com_atakmap_map_layer_raster_tilereader_opengl_GLQuadTileNode2_VertexCoordInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
