/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_opengl_GLRenderBatch2 */

#ifndef _Included_com_atakmap_opengl_GLRenderBatch2
#define _Included_com_atakmap_opengl_GLRenderBatch2
#ifdef __cplusplus
extern "C" {
#endif
#undef com_atakmap_opengl_GLRenderBatch2_HINT_UNTEXTURED
#define com_atakmap_opengl_GLRenderBatch2_HINT_UNTEXTURED 1L
#undef com_atakmap_opengl_GLRenderBatch2_HINT_SOFTWARE_TRANSFORMS
#define com_atakmap_opengl_GLRenderBatch2_HINT_SOFTWARE_TRANSFORMS 2L
#undef com_atakmap_opengl_GLRenderBatch2_HINT_LINES
#define com_atakmap_opengl_GLRenderBatch2_HINT_LINES 4L
#undef com_atakmap_opengl_GLRenderBatch2_HINT_TWO_DIMENSION
#define com_atakmap_opengl_GLRenderBatch2_HINT_TWO_DIMENSION 8L
/*
 * Class:     com_atakmap_opengl_GLRenderBatch2
 * Method:    setMaxTextureUnits
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLRenderBatch2_setMaxTextureUnits
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_atakmap_opengl_GLRenderBatch2
 * Method:    create
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_opengl_GLRenderBatch2_create
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_atakmap_opengl_GLRenderBatch2
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLRenderBatch2_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_opengl_GLRenderBatch2
 * Method:    begin
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLRenderBatch2_begin
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_atakmap_opengl_GLRenderBatch2
 * Method:    end
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLRenderBatch2_end
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_opengl_GLRenderBatch2
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLRenderBatch2_release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_opengl_GLRenderBatch2
 * Method:    setMatrix
 * Signature: (JI[FI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLRenderBatch2_setMatrix
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jint);

/*
 * Class:     com_atakmap_opengl_GLRenderBatch2
 * Method:    pushMatrix
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLRenderBatch2_pushMatrix
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_atakmap_opengl_GLRenderBatch2
 * Method:    popMatrix
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLRenderBatch2_popMatrix
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_atakmap_opengl_GLRenderBatch2
 * Method:    setLineWidth
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLRenderBatch2_setLineWidth
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_atakmap_opengl_GLRenderBatch2
 * Method:    batch
 * Signature: (JIIIIILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLRenderBatch2_batch__JIIIIILjava_nio_FloatBuffer_2IILjava_nio_FloatBuffer_2IFFFF
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jobject, jint, jint, jobject, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_atakmap_opengl_GLRenderBatch2
 * Method:    batch
 * Signature: (JIIIIILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IILjava/nio/ShortBuffer;IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLRenderBatch2_batch__JIIIIILjava_nio_FloatBuffer_2IILjava_nio_FloatBuffer_2IILjava_nio_ShortBuffer_2IFFFF
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jobject, jint, jint, jobject, jint, jint, jobject, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_atakmap_opengl_GLRenderBatch2
 * Method:    batch
 * Signature: (JFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLRenderBatch2_batch__JFFFFFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_atakmap_opengl_GLRenderBatch2
 * Method:    batch
 * Signature: (JFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLRenderBatch2_batch__JFFFFFFFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_atakmap_opengl_GLRenderBatch2
 * Method:    batch
 * Signature: (JIFFFFFFFFFFFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLRenderBatch2_batch__JIFFFFFFFFFFFFFFFFFFFF
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_atakmap_opengl_GLRenderBatch2
 * Method:    batch
 * Signature: (JIFFFFFFFFFFFFFFFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLRenderBatch2_batch__JIFFFFFFFFFFFFFFFFFFFFFFFF
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
