/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_opengl_GLResolvable */

#ifndef _Included_com_atakmap_opengl_GLResolvable
#define _Included_com_atakmap_opengl_GLResolvable
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_opengl_GLResolvable_State */

#ifndef _Included_com_atakmap_opengl_GLResolvable_State
#define _Included_com_atakmap_opengl_GLResolvable_State
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
