/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_opengl_GLText */

#ifndef _Included_com_atakmap_opengl_GLText
#define _Included_com_atakmap_opengl_GLText
#ifdef __cplusplus
extern "C" {
#endif
#undef com_atakmap_opengl_GLText_CHAR_BATCH_SIZE
#define com_atakmap_opengl_GLText_CHAR_BATCH_SIZE 80L
/*
 * Class:     com_atakmap_opengl_GLText
 * Method:    intern
 * Signature: (Lcom/atakmap/android/maps/MapTextFormat;Lcom/atakmap/android/maps/MapTextFormat;)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_opengl_GLText_intern
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_atakmap_opengl_GLText
 * Method:    invalidate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLText_invalidate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_opengl_GLText
 * Method:    batch
 * Signature: (JJLjava/lang/String;FFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLText_batch__JJLjava_lang_String_2FFFFFFF
  (JNIEnv *, jclass, jlong, jlong, jstring, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_atakmap_opengl_GLText
 * Method:    batch
 * Signature: (JJLjava/lang/String;FFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_GLText_batch__JJLjava_lang_String_2FFFFFFFFF
  (JNIEnv *, jclass, jlong, jlong, jstring, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
