/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_coremap_io_IOProviderFactory */

#ifndef _Included_com_atakmap_coremap_io_IOProviderFactory
#define _Included_com_atakmap_coremap_io_IOProviderFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_coremap_io_IOProviderFactory
 * Method:    installFactory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_coremap_io_IOProviderFactory_installFactory
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_coremap_io_IOProviderFactory
 * Method:    uninstallFactory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_coremap_io_IOProviderFactory_uninstallFactory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_coremap_io_IOProviderFactory
 * Method:    DatabaseProvider_create
 * Signature: (Ljava/lang/String;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_coremap_io_IOProviderFactory_DatabaseProvider_1create
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
