/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_projection_MapProjectionDisplayModel */

#ifndef _Included_com_atakmap_map_projection_MapProjectionDisplayModel
#define _Included_com_atakmap_map_projection_MapProjectionDisplayModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_projection_MapProjectionDisplayModel
 * Method:    isSupported
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_projection_MapProjectionDisplayModel_isSupported
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_atakmap_map_projection_MapProjectionDisplayModel
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_projection_MapProjectionDisplayModel_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_projection_MapProjectionDisplayModel
 * Method:    registerImpl
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_projection_MapProjectionDisplayModel_registerImpl
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_projection_MapProjectionDisplayModel
 * Method:    unregisterImpl
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_projection_MapProjectionDisplayModel_unregisterImpl
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_projection_MapProjectionDisplayModel
 * Method:    create
 * Signature: (IJDDDZ)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_projection_MapProjectionDisplayModel_create
  (JNIEnv *, jclass, jint, jlong, jdouble, jdouble, jdouble, jboolean);

/*
 * Class:     com_atakmap_map_projection_MapProjectionDisplayModel
 * Method:    wrap
 * Signature: (ILcom/atakmap/math/GeometryModel;DDDZ)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_projection_MapProjectionDisplayModel_wrap
  (JNIEnv *, jclass, jint, jobject, jdouble, jdouble, jdouble, jboolean);

/*
 * Class:     com_atakmap_map_projection_MapProjectionDisplayModel
 * Method:    get
 * Signature: (I)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_projection_MapProjectionDisplayModel_get
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_atakmap_map_projection_MapProjectionDisplayModel
 * Method:    getEarth
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_projection_MapProjectionDisplayModel_getEarth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_projection_MapProjectionDisplayModel
 * Method:    getSRID
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_projection_MapProjectionDisplayModel_getSRID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_projection_MapProjectionDisplayModel
 * Method:    getZIsHeight
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_projection_MapProjectionDisplayModel_getZIsHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_projection_MapProjectionDisplayModel
 * Method:    getProjectionXToNominalMeters
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_projection_MapProjectionDisplayModel_getProjectionXToNominalMeters
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_projection_MapProjectionDisplayModel
 * Method:    getProjectionYToNominalMeters
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_projection_MapProjectionDisplayModel_getProjectionYToNominalMeters
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_projection_MapProjectionDisplayModel
 * Method:    getProjectionZToNominalMeters
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_projection_MapProjectionDisplayModel_getProjectionZToNominalMeters
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
