/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_math_Matrix */

#ifndef _Included_com_atakmap_math_Matrix
#define _Included_com_atakmap_math_Matrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_math_Matrix
 * Method:    clone
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_math_Matrix_clone
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    create
 * Signature: ()Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_math_Matrix_create__
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    create
 * Signature: (DDDDDDDDDDDDDDDD)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_math_Matrix_create__DDDDDDDDDDDDDDDD
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    transform
 * Signature: (JDDDLcom/atakmap/math/PointD;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_transform
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jobject);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    createInverse
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_math_Matrix_createInverse
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    concatenate
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_concatenate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    preConcatenate
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_preConcatenate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    set
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_set__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    set
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_set__JIID
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    getRowMajor
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_getRowMajor
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    getColumnMajor
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_getColumnMajor
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    get
 * Signature: (JII)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_Matrix_get
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    translate
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_translate__JDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    translate
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_translate__JDDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    rotate
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_rotate__JD
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    rotate
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_rotate__JDDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    rotate
 * Signature: (JDDDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_rotate__JDDDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    rotate
 * Signature: (JDDDDDDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_rotate__JDDDDDDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    scale
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_scale__JD
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    scale
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_scale__JDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    scale
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_scale__JDDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    setToIdentity
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_setToIdentity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    setToTranslate
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_setToTranslate__JDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    setToTranslate
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_setToTranslate__JDDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    setToRotate
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_setToRotate__JD
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    setToRotate
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_setToRotate__JDDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    setToScale
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_setToScale__JD
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    setToScale
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_setToScale__JDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    setToScale
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_Matrix_setToScale__JDDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_Matrix
 * Method:    mapQuadsNative
 * Signature: (DDDDDDDDDDDDDDDD)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_math_Matrix_mapQuadsNative
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_math_Matrix_MatrixOrder */

#ifndef _Included_com_atakmap_math_Matrix_MatrixOrder
#define _Included_com_atakmap_math_Matrix_MatrixOrder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
