/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_math_Mesh */

#ifndef _Included_com_atakmap_math_Mesh
#define _Included_com_atakmap_math_Mesh
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_math_Mesh
 * Method:    create
 * Signature: ([DII)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_math_Mesh_create
  (JNIEnv *, jclass, jdoubleArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
