/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_model_Model */

#ifndef _Included_com_atakmap_map_layer_model_Model
#define _Included_com_atakmap_map_layer_model_Model
#ifdef __cplusplus
extern "C" {
#endif
#undef com_atakmap_map_layer_model_Model_INSTANCE_ID_NONE
#define com_atakmap_map_layer_model_Model_INSTANCE_ID_NONE 0L
#ifdef __cplusplus
}
#endif
#endif
