/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_model_Models */

#ifndef _Included_com_atakmap_map_layer_model_Models
#define _Included_com_atakmap_map_layer_model_Models
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_model_Models
 * Method:    intersect
 * Signature: (IIIJIIJDDDDDD[DLcom/atakmap/math/PointD;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_model_Models_intersect__IIIJIIJDDDDDD_3DLcom_atakmap_math_PointD_2
  (JNIEnv *, jclass, jint, jint, jint, jlong, jint, jint, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdoubleArray, jobject);

/*
 * Class:     com_atakmap_map_layer_model_Models
 * Method:    intersect
 * Signature: (JDDDDDD[DLcom/atakmap/math/PointD;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_model_Models_intersect__JDDDDDD_3DLcom_atakmap_math_PointD_2
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdoubleArray, jobject);

/*
 * Class:     com_atakmap_map_layer_model_Models
 * Method:    transform
 * Signature: (Lcom/atakmap/interop/Pointer;IIIIIIIIIIIIIZ)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_model_Models_transform__Lcom_atakmap_interop_Pointer_2IIIIIIIIIIIIIZ
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     com_atakmap_map_layer_model_Models
 * Method:    transform
 * Signature: (Lcom/atakmap/interop/Pointer;I[DIZ[DLcom/atakmap/interop/ProgressCallback;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_model_Models_transform__Lcom_atakmap_interop_Pointer_2I_3DIZ_3DLcom_atakmap_interop_ProgressCallback_2
  (JNIEnv *, jclass, jobject, jint, jdoubleArray, jint, jboolean, jdoubleArray, jobject);

/*
 * Class:     com_atakmap_map_layer_model_Models
 * Method:    adapt
 * Signature: (Lcom/atakmap/map/layer/model/Mesh;Ljava/lang/String;IIZIIJIJJJJIIDDDDDDIIIIIIIIIIIIIZ)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_model_Models_adapt
  (JNIEnv *, jclass, jobject, jstring, jint, jint, jboolean, jint, jint, jlong, jint, jlong, jlong, jlong, jlong, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_model_Models_OnTransformProgressListener */

#ifndef _Included_com_atakmap_map_layer_model_Models_OnTransformProgressListener
#define _Included_com_atakmap_map_layer_model_Models_OnTransformProgressListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
