/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_model_ModelBuilder */

#ifndef _Included_com_atakmap_map_layer_model_ModelBuilder
#define _Included_com_atakmap_map_layer_model_ModelBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    create
 * Signature: (II)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_create__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    create
 * Signature: (III)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_create__III
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    create
 * Signature: (IIIIIIIIIIIIIIZ)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_create__IIIIIIIIIIIIIIZ
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    create
 * Signature: (IIIIIIIIIIIIIIZI)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_create__IIIIIIIIIIIIIIZI
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jboolean, jint);

/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    reserveVertices
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_reserveVertices
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    reserveIndices
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_reserveIndices
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    setWindingOrder
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_setWindingOrder
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    addMaterial
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_addMaterial
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    addVertex
 * Signature: (JDDDFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_addVertex__JDDDFFFFFFFFF
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    addVertex
 * Signature: (JDDD[FFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_addVertex__JDDD_3FFFFFFFF
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jfloatArray, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    addIndex
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_addIndex
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    build
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_build__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    build
 * Signature: (IIIIII[I[I[IIIIIIII[I[Ljava/lang/String;[IDDDDDDILjava/nio/Buffer;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_build__IIIIII_3I_3I_3IIIIIIII_3I_3Ljava_lang_String_2_3IDDDDDDILjava_nio_Buffer_2
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jintArray, jintArray, jintArray, jint, jint, jint, jint, jint, jint, jint, jintArray, jobjectArray, jintArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jobject);

/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    build
 * Signature: (IIIIII[I[I[IIIIIIII[I[Ljava/lang/String;[IDDDDDDILjava/nio/Buffer;IILjava/nio/Buffer;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_build__IIIIII_3I_3I_3IIIIIIII_3I_3Ljava_lang_String_2_3IDDDDDDILjava_nio_Buffer_2IILjava_nio_Buffer_2
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jintArray, jintArray, jintArray, jint, jint, jint, jint, jint, jint, jint, jintArray, jobjectArray, jintArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jobject, jint, jint, jobject);

/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    build
 * Signature: (IIIIII[I[I[IIIIIIII[I[Ljava/lang/String;[IDDDDDDILjava/nio/Buffer;[Ljava/nio/Buffer;Ljava/nio/Buffer;Ljava/nio/Buffer;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_build__IIIIII_3I_3I_3IIIIIIII_3I_3Ljava_lang_String_2_3IDDDDDDILjava_nio_Buffer_2_3Ljava_nio_Buffer_2Ljava_nio_Buffer_2Ljava_nio_Buffer_2
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jintArray, jintArray, jintArray, jint, jint, jint, jint, jint, jint, jint, jintArray, jobjectArray, jintArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jobject, jobjectArray, jobject, jobject);

/*
 * Class:     com_atakmap_map_layer_model_ModelBuilder
 * Method:    build
 * Signature: (IIIIII[I[I[IIIIIIII[I[Ljava/lang/String;[IDDDDDDILjava/nio/Buffer;[Ljava/nio/Buffer;Ljava/nio/Buffer;Ljava/nio/Buffer;IILjava/nio/Buffer;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_model_ModelBuilder_build__IIIIII_3I_3I_3IIIIIIII_3I_3Ljava_lang_String_2_3IDDDDDDILjava_nio_Buffer_2_3Ljava_nio_Buffer_2Ljava_nio_Buffer_2Ljava_nio_Buffer_2IILjava_nio_Buffer_2
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jintArray, jintArray, jintArray, jint, jint, jint, jint, jint, jint, jint, jintArray, jobjectArray, jintArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jobject, jobjectArray, jobject, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_model_ModelBuilder_ReferenceMeshReference */

#ifndef _Included_com_atakmap_map_layer_model_ModelBuilder_ReferenceMeshReference
#define _Included_com_atakmap_map_layer_model_ModelBuilder_ReferenceMeshReference
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_model_ModelBuilder_InstancedMeshReference */

#ifndef _Included_com_atakmap_map_layer_model_ModelBuilder_InstancedMeshReference
#define _Included_com_atakmap_map_layer_model_ModelBuilder_InstancedMeshReference
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_model_ModelBuilder_BuilderMeshReference */

#ifndef _Included_com_atakmap_map_layer_model_ModelBuilder_BuilderMeshReference
#define _Included_com_atakmap_map_layer_model_ModelBuilder_BuilderMeshReference
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_model_ModelBuilder_MeshReference */

#ifndef _Included_com_atakmap_map_layer_model_ModelBuilder_MeshReference
#define _Included_com_atakmap_map_layer_model_ModelBuilder_MeshReference
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_model_ModelBuilder_ModelImpl */

#ifndef _Included_com_atakmap_map_layer_model_ModelBuilder_ModelImpl
#define _Included_com_atakmap_map_layer_model_ModelBuilder_ModelImpl
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
