/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_feature_falconview_FalconViewFeatureDataSource */

#ifndef _Included_com_atakmap_map_layer_feature_falconview_FalconViewFeatureDataSource
#define _Included_com_atakmap_map_layer_feature_falconview_FalconViewFeatureDataSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_feature_falconview_FalconViewFeatureDataSource
 * Method:    parse
 * Signature: (Ljava/lang/String;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_falconview_FalconViewFeatureDataSource_parse
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_atakmap_map_layer_feature_falconview_FalconViewFeatureDataSource
 * Method:    registerProvider
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_falconview_FalconViewFeatureDataSource_registerProvider
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_feature_falconview_FalconViewFeatureDataSource_DBCreator */

#ifndef _Included_com_atakmap_map_layer_feature_falconview_FalconViewFeatureDataSource_DBCreator
#define _Included_com_atakmap_map_layer_feature_falconview_FalconViewFeatureDataSource_DBCreator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
