/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_feature_NativeFileCursor */

#ifndef _Included_com_atakmap_map_layer_feature_NativeFileCursor
#define _Included_com_atakmap_map_layer_feature_NativeFileCursor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_feature_NativeFileCursor
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFileCursor_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFileCursor
 * Method:    getFile
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_layer_feature_NativeFileCursor_getFile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFileCursor
 * Method:    moveToNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_NativeFileCursor_moveToNext
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
