/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_elevation_NativeElevationChunk */

#ifndef _Included_com_atakmap_map_elevation_NativeElevationChunk
#define _Included_com_atakmap_map_elevation_NativeElevationChunk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_elevation_NativeElevationChunk
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_elevation_NativeElevationChunk_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationChunk
 * Method:    getResolution
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_elevation_NativeElevationChunk_getResolution
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationChunk
 * Method:    isAuthoritative
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_elevation_NativeElevationChunk_isAuthoritative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationChunk
 * Method:    getCE
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_elevation_NativeElevationChunk_getCE
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationChunk
 * Method:    getLE
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_elevation_NativeElevationChunk_getLE
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationChunk
 * Method:    getUri
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_elevation_NativeElevationChunk_getUri
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationChunk
 * Method:    getType
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_elevation_NativeElevationChunk_getType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationChunk
 * Method:    getBounds
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_elevation_NativeElevationChunk_getBounds
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationChunk
 * Method:    getFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_elevation_NativeElevationChunk_getFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationChunk
 * Method:    createData
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_elevation_NativeElevationChunk_createData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationChunk
 * Method:    Data_destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_elevation_NativeElevationChunk_Data_1destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationChunk
 * Method:    Data_getLocalFrame
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_elevation_NativeElevationChunk_Data_1getLocalFrame
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationChunk
 * Method:    Data_isInterpolated
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_elevation_NativeElevationChunk_Data_1isInterpolated
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationChunk
 * Method:    Data_getSrid
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_elevation_NativeElevationChunk_Data_1getSrid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationChunk
 * Method:    Data_getValue
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_elevation_NativeElevationChunk_Data_1getValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
