/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_model_NativeMesh */

#ifndef _Included_com_atakmap_map_layer_model_NativeMesh
#define _Included_com_atakmap_map_layer_model_NativeMesh
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getNumMaterials
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getNumMaterials
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getMaterialTextureUri
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getMaterialTextureUri
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getMaterialColor
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getMaterialColor
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getMaterialTextureIndex
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getMaterialTextureIndex
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getNumVertices
 * Signature: (Lcom/atakmap/interop/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getNumVertices
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getNumFaces
 * Signature: (Lcom/atakmap/interop/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getNumFaces
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    isIndexed
 * Signature: (Lcom/atakmap/interop/Pointer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_model_NativeMesh_isIndexed
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getPosition
 * Signature: (Lcom/atakmap/interop/Pointer;ILcom/atakmap/math/PointD;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getPosition
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTextureCoordinate
 * Signature: (Lcom/atakmap/interop/Pointer;IILcom/atakmap/math/PointD;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTextureCoordinate
  (JNIEnv *, jclass, jobject, jint, jint, jobject);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getNormal
 * Signature: (Lcom/atakmap/interop/Pointer;ILcom/atakmap/math/PointD;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getNormal
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getColor
 * Signature: (Lcom/atakmap/interop/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getColor
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getVertexDataLayout
 * Signature: (Lcom/atakmap/interop/Pointer;)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getVertexDataLayout
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getIndexType
 * Signature: (Lcom/atakmap/interop/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getIndexType
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getIndex
 * Signature: (Lcom/atakmap/interop/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getIndex
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getIndices
 * Signature: (Lcom/atakmap/interop/Pointer;Ljava/lang/Object;)Ljava/nio/Buffer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getIndices
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getIndexOffset
 * Signature: (Lcom/atakmap/interop/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getIndexOffset
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getVertices
 * Signature: (Lcom/atakmap/interop/Pointer;I)Ljava/nio/Buffer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getVertices
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getFaceWindingOrder
 * Signature: (Lcom/atakmap/interop/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getFaceWindingOrder
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getDrawMode
 * Signature: (Lcom/atakmap/interop/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getDrawMode
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getAABB
 * Signature: (Lcom/atakmap/interop/Pointer;[D)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getAABB
  (JNIEnv *, jclass, jobject, jdoubleArray);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_model_NativeMesh_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEWO_Clockwise
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEWO_1Clockwise
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEWO_CounterClockwise
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEWO_1CounterClockwise
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEWO_Undefined
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEWO_1Undefined
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEDM_Points
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEDM_1Points
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEDM_Triangles
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEDM_1Triangles
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEDM_TriangleStrip
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEDM_1TriangleStrip
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEDM_Lines
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEDM_1Lines
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEDM_LineStrip
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEDM_1LineStrip
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEVA_Position
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEVA_1Position
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEVA_TexCoord0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEVA_1TexCoord0
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEVA_TexCoord1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEVA_1TexCoord1
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEVA_TexCoord2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEVA_1TexCoord2
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEVA_TexCoord3
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEVA_1TexCoord3
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEVA_TexCoord4
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEVA_1TexCoord4
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEVA_TexCoord5
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEVA_1TexCoord5
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEVA_TexCoord6
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEVA_1TexCoord6
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEVA_TexCoord7
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEVA_1TexCoord7
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEVA_Normal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEVA_1Normal
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_model_NativeMesh
 * Method:    getTEVA_Color
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_NativeMesh_getTEVA_1Color
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
