/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_opengl_NativeGLLayer3 */

#ifndef _Included_com_atakmap_map_layer_opengl_NativeGLLayer3
#define _Included_com_atakmap_map_layer_opengl_NativeGLLayer3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_opengl_NativeGLLayer3
 * Method:    start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_opengl_NativeGLLayer3_start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_opengl_NativeGLLayer3
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_opengl_NativeGLLayer3_stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_opengl_NativeGLLayer3
 * Method:    getSubject
 * Signature: (J)Lcom/atakmap/map/layer/Layer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_opengl_NativeGLLayer3_getSubject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_opengl_NativeGLLayer3
 * Method:    draw
 * Signature: (JLcom/atakmap/map/opengl/GLMapView;I)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_opengl_NativeGLLayer3_draw
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     com_atakmap_map_layer_opengl_NativeGLLayer3
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_opengl_NativeGLLayer3_release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_opengl_NativeGLLayer3
 * Method:    getRenderPass
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_opengl_NativeGLLayer3_getRenderPass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_opengl_NativeGLLayer3
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_opengl_NativeGLLayer3_destruct
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
