/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_interop_NativeRunnable */

#ifndef _Included_com_atakmap_interop_NativeRunnable
#define _Included_com_atakmap_interop_NativeRunnable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_interop_NativeRunnable
 * Method:    run
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_interop_NativeRunnable_run
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_interop_NativeRunnable
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_interop_NativeRunnable_destruct
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
