/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_feature_NativeFeatureDataStore2 */

#ifndef _Included_com_atakmap_map_layer_feature_NativeFeatureDataStore2
#define _Included_com_atakmap_map_layer_feature_NativeFeatureDataStore2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    FeatureQueryParameters_create
 * Signature: ()Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_FeatureQueryParameters_1create
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    FeatureQueryParameters_destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_FeatureQueryParameters_1destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    FeatureQueryParameters_setFeatureSetFilter
 * Signature: (J[J[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;DDZII)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_FeatureQueryParameters_1setFeatureSetFilter
  (JNIEnv *, jclass, jlong, jlongArray, jobjectArray, jobjectArray, jobjectArray, jdouble, jdouble, jboolean, jint, jint);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    FeatureQueryParameters_set
 * Signature: (J[J[Ljava/lang/String;[IZJJJII[I[DI[I[DIIJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_FeatureQueryParameters_1set
  (JNIEnv *, jclass, jlong, jlongArray, jobjectArray, jintArray, jboolean, jlong, jlong, jlong, jint, jint, jintArray, jdoubleArray, jint, jintArray, jdoubleArray, jint, jint, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    FeatureSetQueryParameters_create
 * Signature: ()Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_FeatureSetQueryParameters_1create
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    FeatureSetQueryParameters_destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_FeatureSetQueryParameters_1destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    FeatureSetQueryParameters_set
 * Signature: (J[J[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;DDZII)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_FeatureSetQueryParameters_1set
  (JNIEnv *, jclass, jlong, jlongArray, jobjectArray, jobjectArray, jobjectArray, jdouble, jdouble, jboolean, jint, jint);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    queryFeatures
 * Signature: (JJ)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_queryFeatures
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    queryFeaturesCount
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_queryFeaturesCount
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    queryFeatureSets
 * Signature: (JJ)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_queryFeatureSets
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    queryFeatureSetsCount
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_queryFeatureSetsCount
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    insertFeature
 * Signature: (JJJLjava/lang/String;ILjava/lang/Object;ILjava/lang/Object;JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_insertFeature__JJJLjava_lang_String_2ILjava_lang_Object_2ILjava_lang_Object_2JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong, jstring, jint, jobject, jint, jobject, jlong, jlong, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    insertFeature
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_insertFeature__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    insertFeatureSet
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;DDJ)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_insertFeatureSet
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring, jstring, jdouble, jdouble, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    updateFeature
 * Signature: (JJILjava/lang/String;JJJI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_updateFeature
  (JNIEnv *, jclass, jlong, jlong, jint, jstring, jlong, jlong, jlong, jint);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    updateFeatureSet
 * Signature: (JJLjava/lang/String;DD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_updateFeatureSet__JJLjava_lang_String_2DD
  (JNIEnv *, jclass, jlong, jlong, jstring, jdouble, jdouble);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    updateFeatureSet
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_updateFeatureSet__JJLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    updateFeatureSet
 * Signature: (JJDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_updateFeatureSet__JJDD
  (JNIEnv *, jclass, jlong, jlong, jdouble, jdouble);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    deleteFeature
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_deleteFeature
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    deleteFeatures
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_deleteFeatures
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    deleteFeatureSet
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_deleteFeatureSet
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    deleteFeatureSets
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_deleteFeatureSets
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    setFeatureVisible
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_setFeatureVisible
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    setFeaturesVisible
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_setFeaturesVisible
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    setFeatureSetVisible
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_setFeatureSetVisible
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    setFeatureSetsVisible
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_setFeatureSetsVisible
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    hasTimeReference
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_hasTimeReference
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getMinimumTimestamp
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getMinimumTimestamp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getMaximumTimestamp
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getMaximumTimestamp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getUri
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getUri
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    supportsExplicitIDs
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_supportsExplicitIDs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getModificationFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getModificationFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getVisibilityFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getVisibilityFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    hasCache
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_hasCache
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    clearCache
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_clearCache
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getCacheSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getCacheSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    acquireModifyLock
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_acquireModifyLock
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    releaseModifyLock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_releaseModifyLock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    addOnDataStoreContentChangedListener
 * Signature: (JLcom/atakmap/interop/NotifyCallback;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_addOnDataStoreContentChangedListener
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    removeOnDataStoreContentChangedListener
 * Signature: (JLcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_removeOnDataStoreContentChangedListener
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFEATURE_ID_NONE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFEATURE_1ID_1NONE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFEATURESET_ID_NONE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFEATURESET_1ID_1NONE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFEATURE_VERSION_NONE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFEATURE_1VERSION_1NONE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFEATURESET_VERSION_NONE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFEATURESET_1VERSION_1NONE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getVISIBILITY_SETTINGS_FEATURE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getVISIBILITY_1SETTINGS_1FEATURE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getVISIBILITY_SETTINGS_FEATURESET
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getVISIBILITY_1SETTINGS_1FEATURESET
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getMODIFY_BULK_MODIFICATIONS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getMODIFY_1BULK_1MODIFICATIONS
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getMODIFY_FEATURESET_INSERT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getMODIFY_1FEATURESET_1INSERT
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getMODIFY_FEATURESET_UPDATE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getMODIFY_1FEATURESET_1UPDATE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getMODIFY_FEATURESET_DELETE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getMODIFY_1FEATURESET_1DELETE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getMODIFY_FEATURESET_FEATURE_INSERT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getMODIFY_1FEATURESET_1FEATURE_1INSERT
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getMODIFY_FEATURESET_FEATURE_UPDATE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getMODIFY_1FEATURESET_1FEATURE_1UPDATE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getMODIFY_FEATURESET_FEATURE_DELETE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getMODIFY_1FEATURESET_1FEATURE_1DELETE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getMODIFY_FEATURESET_NAME
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getMODIFY_1FEATURESET_1NAME
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getMODIFY_FEATURESET_DISPLAY_THRESHOLDS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getMODIFY_1FEATURESET_1DISPLAY_1THRESHOLDS
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getMODIFY_FEATURE_NAME
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getMODIFY_1FEATURE_1NAME
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getMODIFY_FEATURE_GEOMETRY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getMODIFY_1FEATURE_1GEOMETRY
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getMODIFY_FEATURE_STYLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getMODIFY_1FEATURE_1STYLE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getMODIFY_FEATURE_ATTRIBUTES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getMODIFY_1FEATURE_1ATTRIBUTES
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getTIMESTAMP_NONE
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getTIMESTAMP_1NONE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFIELD_GEOMETRY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFIELD_1GEOMETRY
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFIELD_NAME
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFIELD_1NAME
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFIELD_ATTRIBUTES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFIELD_1ATTRIBUTES
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFIELD_STYLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFIELD_1STYLE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getUPDATE_ATTRIBUTES_ADD_OR_REPLACE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getUPDATE_1ATTRIBUTES_1ADD_1OR_1REPLACE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getUPDATE_ATTRIBUTES_SET
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getUPDATE_1ATTRIBUTES_1SET
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFeatureQueryParamters_IgnoreFields_GeometryField
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFeatureQueryParamters_1IgnoreFields_1GeometryField
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFeatureQueryParamters_IgnoreFields_StyleField
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFeatureQueryParamters_1IgnoreFields_1StyleField
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFeatureQueryParamters_IgnoreFields_AttributesField
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFeatureQueryParamters_1IgnoreFields_1AttributesField
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFeatureQueryParamters_IgnoreFields_NameField
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFeatureQueryParamters_1IgnoreFields_1NameField
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFeatureQueryParamters_Order_Type_Resolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFeatureQueryParamters_1Order_1Type_1Resolution
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFeatureQueryParamters_Order_Type_FeatureSet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFeatureQueryParamters_1Order_1Type_1FeatureSet
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFeatureQueryParamters_Order_Type_FeatureName
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFeatureQueryParamters_1Order_1Type_1FeatureName
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFeatureQueryParamters_Order_Type_FeatureId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFeatureQueryParamters_1Order_1Type_1FeatureId
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFeatureQueryParamters_Order_Type_Distance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFeatureQueryParamters_1Order_1Type_1Distance
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFeatureQueryParamters_Order_Type_GeometryType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFeatureQueryParamters_1Order_1Type_1GeometryType
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFeatureQueryParamters_SpatialOp_Type_Buffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFeatureQueryParamters_1SpatialOp_1Type_1Buffer
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataStore2
 * Method:    getFeatureQueryParamters_SpatialOp_Type_Simplify
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataStore2_getFeatureQueryParamters_1SpatialOp_1Type_1Simplify
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_feature_NativeFeatureDataStore2_CallbackForwarder */

#ifndef _Included_com_atakmap_map_layer_feature_NativeFeatureDataStore2_CallbackForwarder
#define _Included_com_atakmap_map_layer_feature_NativeFeatureDataStore2_CallbackForwarder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
