/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_math_NativeGeometryModel */

#ifndef _Included_com_atakmap_math_NativeGeometryModel
#define _Included_com_atakmap_math_NativeGeometryModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_math_NativeGeometryModel_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    intersect
 * Signature: (JDDDDDDLcom/atakmap/math/PointD;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_math_NativeGeometryModel_intersect
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jobject);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    getGeomClass
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_math_NativeGeometryModel_getGeomClass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    clone
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_math_NativeGeometryModel_clone
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    isWrapped
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_math_NativeGeometryModel_isWrapped
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    unwrap
 * Signature: (J)Lcom/atakmap/math/GeometryModel;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_math_NativeGeometryModel_unwrap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    wrap
 * Signature: (Lcom/atakmap/math/GeometryModel;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_math_NativeGeometryModel_wrap
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    Ellipsoid_create
 * Signature: (DDDDDD)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_math_NativeGeometryModel_Ellipsoid_1create
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    Ellipsoid_getCenterX
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_NativeGeometryModel_Ellipsoid_1getCenterX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    Ellipsoid_getCenterY
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_NativeGeometryModel_Ellipsoid_1getCenterY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    Ellipsoid_getCenterZ
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_NativeGeometryModel_Ellipsoid_1getCenterZ
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    Ellipsoid_getRadiusX
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_NativeGeometryModel_Ellipsoid_1getRadiusX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    Ellipsoid_getRadiusY
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_NativeGeometryModel_Ellipsoid_1getRadiusY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    Ellipsoid_getRadiusZ
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_NativeGeometryModel_Ellipsoid_1getRadiusZ
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    Sphere_create
 * Signature: (DDDD)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_math_NativeGeometryModel_Sphere_1create
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    Sphere_getCenterX
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_NativeGeometryModel_Sphere_1getCenterX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    Sphere_getCenterY
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_NativeGeometryModel_Sphere_1getCenterY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    Sphere_getCenterZ
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_NativeGeometryModel_Sphere_1getCenterZ
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    Sphere_getRadius
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_NativeGeometryModel_Sphere_1getRadius
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    AABB_create
 * Signature: (DDDDDD)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_math_NativeGeometryModel_AABB_1create
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    AABB_getMinX
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_NativeGeometryModel_AABB_1getMinX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    AABB_getMinY
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_NativeGeometryModel_AABB_1getMinY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    AABB_getMinZ
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_NativeGeometryModel_AABB_1getMinZ
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    AABB_getMaxX
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_NativeGeometryModel_AABB_1getMaxX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    AABB_getMaxY
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_NativeGeometryModel_AABB_1getMaxY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    AABB_getMaxZ
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_math_NativeGeometryModel_AABB_1getMaxZ
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    Plane_create
 * Signature: (DDDDDD)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_math_NativeGeometryModel_Plane_1create
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    getGeometryModel2_GeometryClass_PLANE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_math_NativeGeometryModel_getGeometryModel2_1GeometryClass_1PLANE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    getGeometryModel2_GeometryClass_ELLIPSOID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_math_NativeGeometryModel_getGeometryModel2_1GeometryClass_1ELLIPSOID
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    getGeometryModel2_GeometryClass_SPHERE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_math_NativeGeometryModel_getGeometryModel2_1GeometryClass_1SPHERE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    getGeometryModel2_GeometryClass_TRIANGLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_math_NativeGeometryModel_getGeometryModel2_1GeometryClass_1TRIANGLE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    getGeometryModel2_GeometryClass_MESH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_math_NativeGeometryModel_getGeometryModel2_1GeometryClass_1MESH
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    getGeometryModel2_GeometryClass_AABB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_math_NativeGeometryModel_getGeometryModel2_1GeometryClass_1AABB
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_math_NativeGeometryModel
 * Method:    getGeometryModel2_GeometryClass_UNDEFINED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_math_NativeGeometryModel_getGeometryModel2_1GeometryClass_1UNDEFINED
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
