/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_opengl_NativeGLLayerSpi2 */

#ifndef _Included_com_atakmap_map_layer_opengl_NativeGLLayerSpi2
#define _Included_com_atakmap_map_layer_opengl_NativeGLLayerSpi2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_opengl_NativeGLLayerSpi2
 * Method:    getPointer
 * Signature: (Lcom/atakmap/map/layer/opengl/GLLayerSpi2;)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_opengl_NativeGLLayerSpi2_getPointer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_opengl_NativeGLLayerSpi2
 * Method:    wrap
 * Signature: (Lcom/atakmap/map/layer/opengl/GLLayerSpi2;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_opengl_NativeGLLayerSpi2_wrap
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_opengl_NativeGLLayerSpi2
 * Method:    hasPointer
 * Signature: (Lcom/atakmap/map/layer/opengl/GLLayerSpi2;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_opengl_NativeGLLayerSpi2_hasPointer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_opengl_NativeGLLayerSpi2
 * Method:    create
 * Signature: (Lcom/atakmap/interop/Pointer;Ljava/lang/Object;)Lcom/atakmap/map/layer/opengl/GLLayerSpi2;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_opengl_NativeGLLayerSpi2_create__Lcom_atakmap_interop_Pointer_2Ljava_lang_Object_2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_atakmap_map_layer_opengl_NativeGLLayerSpi2
 * Method:    hasObject
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_opengl_NativeGLLayerSpi2_hasObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_opengl_NativeGLLayerSpi2
 * Method:    getObject
 * Signature: (J)Lcom/atakmap/map/layer/opengl/GLLayerSpi2;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_opengl_NativeGLLayerSpi2_getObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_opengl_NativeGLLayerSpi2
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_opengl_NativeGLLayerSpi2_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_opengl_NativeGLLayerSpi2
 * Method:    getPriority
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_opengl_NativeGLLayerSpi2_getPriority
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_opengl_NativeGLLayerSpi2
 * Method:    create
 * Signature: (JLcom/atakmap/map/opengl/GLMapView;Lcom/atakmap/map/layer/Layer;)Lcom/atakmap/map/layer/opengl/GLLayer2;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_opengl_NativeGLLayerSpi2_create__JLcom_atakmap_map_opengl_GLMapView_2Lcom_atakmap_map_layer_Layer_2
  (JNIEnv *, jclass, jlong, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
