/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_opengl_ElMgrTerrainRenderService */

#ifndef _Included_com_atakmap_map_opengl_ElMgrTerrainRenderService
#define _Included_com_atakmap_map_opengl_ElMgrTerrainRenderService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    create
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_create
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    getTerrainVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_getTerrainVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    lock
 * Signature: (JJLjava/util/Collection;)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_lock
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    unlock
 * Signature: (J[Lcom/atakmap/interop/Pointer;I)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_unlock
  (JNIEnv *, jclass, jlong, jobjectArray, jint);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    getElevation
 * Signature: (JDD)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_getElevation
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    TerrainTile_destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_TerrainTile_1destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    TerrainTile_getSkirtIndexOffset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_TerrainTile_1getSkirtIndexOffset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    TerrainTile_getNumIndices
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_TerrainTile_1getNumIndices
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    TerrainTile_getMesh
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_TerrainTile_1getMesh
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    TerrainTile_getLocalFrame
 * Signature: (J)Lcom/atakmap/math/Matrix;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_TerrainTile_1getLocalFrame
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    TerrainTile_getSrid
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_TerrainTile_1getSrid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    TerrainTile_getAAbbWgs84
 * Signature: (JLcom/atakmap/map/layer/feature/geometry/Envelope;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_TerrainTile_1getAAbbWgs84
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    TerrainTile_hasData
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_TerrainTile_1hasData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    TerrainTile_isHeightMap
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_TerrainTile_1isHeightMap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    TerrainTile_getNumPostsX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_TerrainTile_1getNumPostsX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    TerrainTile_getNumPostsY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_TerrainTile_1getNumPostsY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_opengl_ElMgrTerrainRenderService
 * Method:    TerrainTile_isInvertYAxis
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_opengl_ElMgrTerrainRenderService_TerrainTile_1isInvertYAxis
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
