/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_feature_NativeFeatureDataSource */

#ifndef _Included_com_atakmap_map_layer_feature_NativeFeatureDataSource
#define _Included_com_atakmap_map_layer_feature_NativeFeatureDataSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    wrap
 * Signature: (Lcom/atakmap/map/layer/feature/FeatureDataSource;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_wrap
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    FeatureDataSource_destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_FeatureDataSource_1destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    FeatureDataSource_parse
 * Signature: (JLjava/lang/String;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_FeatureDataSource_1parse
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    FeatureDataSource_getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_FeatureDataSource_1getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    FeatureDataSource_parseVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_FeatureDataSource_1parseVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    Content_destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_Content_1destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    Content_getType
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_Content_1getType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    Content_getProvider
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_Content_1getProvider
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    Content_moveToNextFeature
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_Content_1moveToNextFeature
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    Content_moveToNextFeatureSet
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_Content_1moveToNextFeatureSet
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    Content_get
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_Content_1get
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    Content_getFeatureSetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_Content_1getFeatureSetName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    Content_getMinResolution
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_Content_1getMinResolution
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    Content_getMaxResolution
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_Content_1getMaxResolution
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    FeatureDefinition_getRawGeometry
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_FeatureDefinition_1getRawGeometry
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    FeatureDefinition_getGeomCoding
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_FeatureDefinition_1getGeomCoding
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    FeatureDefinition_getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_FeatureDefinition_1getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    FeatureDefinition_getStyleCoding
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_FeatureDefinition_1getStyleCoding
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    FeatureDefinition_getRawStyle
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_FeatureDefinition_1getRawStyle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    FeatureDefinition_getAttributes
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_FeatureDefinition_1getAttributes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    FeatureDataSourceContentFactory_register
 * Signature: (Lcom/atakmap/interop/Pointer;I)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_FeatureDataSourceContentFactory_1register
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    FeatureDataSourceContentFactory_unregister
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_FeatureDataSourceContentFactory_1unregister
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    FeatureDataSourceContentFactory_getProvider
 * Signature: (Ljava/lang/String;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_FeatureDataSourceContentFactory_1getProvider
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    FeatureDataSourceContentFactory_parse
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_FeatureDataSourceContentFactory_1parse
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    getFeatureDefinition_GeometryEncoding_GeomWkt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_getFeatureDefinition_1GeometryEncoding_1GeomWkt
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    getFeatureDefinition_GeometryEncoding_GeomWkb
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_getFeatureDefinition_1GeometryEncoding_1GeomWkb
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    getFeatureDefinition_GeometryEncoding_GeomBlob
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_getFeatureDefinition_1GeometryEncoding_1GeomBlob
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    getFeatureDefinition_GeometryEncoding_GeomGeom
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_getFeatureDefinition_1GeometryEncoding_1GeomGeom
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    getFeatureDefinition_StyleEncoding_StyleOgr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_getFeatureDefinition_1StyleEncoding_1StyleOgr
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureDataSource
 * Method:    getFeatureDefinition_StyleEncoding_StyleStyle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureDataSource_getFeatureDefinition_1StyleEncoding_1StyleStyle
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_feature_NativeFeatureDataSource_NativeContent */

#ifndef _Included_com_atakmap_map_layer_feature_NativeFeatureDataSource_NativeContent
#define _Included_com_atakmap_map_layer_feature_NativeFeatureDataSource_NativeContent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_feature_ogr_OgrFeatureDataSource */

#ifndef _Included_com_atakmap_map_layer_feature_ogr_OgrFeatureDataSource
#define _Included_com_atakmap_map_layer_feature_ogr_OgrFeatureDataSource
#ifdef __cplusplus
extern "C" {
#endif
#undef com_atakmap_map_layer_feature_ogr_OgrFeatureDataSource_GEOMETRY
#define com_atakmap_map_layer_feature_ogr_OgrFeatureDataSource_GEOMETRY 1L
#undef com_atakmap_map_layer_feature_ogr_OgrFeatureDataSource_GEOMETRY_COLLECTION
#define com_atakmap_map_layer_feature_ogr_OgrFeatureDataSource_GEOMETRY_COLLECTION 2L
/*
 * Class:     com_atakmap_map_layer_feature_ogr_OgrFeatureDataSource
 * Method:    create
 * Signature: ()Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_ogr_OgrFeatureDataSource_create
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_ogr_OgrFeatureDataSource
 * Method:    registerDrivers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_ogr_OgrFeatureDataSource_registerDrivers
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
