/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_projection_NativeProjection */

#ifndef _Included_com_atakmap_map_projection_NativeProjection
#define _Included_com_atakmap_map_projection_NativeProjection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_projection_NativeProjection
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_projection_NativeProjection_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_projection_NativeProjection
 * Method:    wrap
 * Signature: (Lcom/atakmap/map/projection/Projection;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_projection_NativeProjection_wrap
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_projection_NativeProjection
 * Method:    isWrapper
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_projection_NativeProjection_isWrapper
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_projection_NativeProjection
 * Method:    unwrap
 * Signature: (J)Lcom/atakmap/map/projection/Projection;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_projection_NativeProjection_unwrap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_projection_NativeProjection
 * Method:    getSrid
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_projection_NativeProjection_getSrid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_projection_NativeProjection
 * Method:    is3D
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_projection_NativeProjection_is3D
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_projection_NativeProjection
 * Method:    forward
 * Signature: (JDDDLcom/atakmap/math/PointD;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_projection_NativeProjection_forward
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jobject);

/*
 * Class:     com_atakmap_map_projection_NativeProjection
 * Method:    inverse
 * Signature: (JDDDLcom/atakmap/coremap/maps/coords/GeoPoint;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_projection_NativeProjection_inverse
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jobject);

/*
 * Class:     com_atakmap_map_projection_NativeProjection
 * Method:    getMinLatitude
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_projection_NativeProjection_getMinLatitude
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_projection_NativeProjection
 * Method:    getMinLongitude
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_projection_NativeProjection_getMinLongitude
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_projection_NativeProjection
 * Method:    getMaxLatitude
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_projection_NativeProjection_getMaxLatitude
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_projection_NativeProjection
 * Method:    getMaxLongitude
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_projection_NativeProjection_getMaxLongitude
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
