/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_elevation_NativeElevationSource */

#ifndef _Included_com_atakmap_map_elevation_NativeElevationSource
#define _Included_com_atakmap_map_elevation_NativeElevationSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    wrap
 * Signature: (Lcom/atakmap/map/elevation/ElevationSource;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_wrap
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    hasObject
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_hasObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    getObject
 * Signature: (J)Lcom/atakmap/map/elevation/ElevationSource;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_getObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    getEnvelope
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_getEnvelope
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    query
 * Signature: (JJ)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_query
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    addOnContentChangedListener
 * Signature: (JLcom/atakmap/interop/NotifyCallback;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_addOnContentChangedListener
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    removeOnContentChangedListener
 * Signature: (JLcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_removeOnContentChangedListener
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    QueryParameters_create
 * Signature: ()Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_QueryParameters_1create
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    QueryParameters_destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_QueryParameters_1destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    QueryParameters_set
 * Signature: (JJDDD[Ljava/lang/String;ZZDD[IZI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_QueryParameters_1set
  (JNIEnv *, jclass, jlong, jlong, jdouble, jdouble, jdouble, jobjectArray, jboolean, jboolean, jdouble, jdouble, jintArray, jboolean, jint);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    QueryParameters_Order_getResolutionAsc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_QueryParameters_1Order_1getResolutionAsc
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    QueryParameters_Order_getResolutionDesc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_QueryParameters_1Order_1getResolutionDesc
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    QueryParameters_Order_getCEAsc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_QueryParameters_1Order_1getCEAsc
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    QueryParameters_Order_getCEDesc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_QueryParameters_1Order_1getCEDesc
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    QueryParameters_Order_getLEAsc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_QueryParameters_1Order_1getLEAsc
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    QueryParameters_Order_getLEDesc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_QueryParameters_1Order_1getLEDesc
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    OnContentChangedListener_onContentChanged
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_OnContentChangedListener_1onContentChanged
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_map_elevation_NativeElevationSource
 * Method:    OnContentChangedListener_destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_elevation_NativeElevationSource_OnContentChangedListener_1destruct
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_elevation_NativeElevationSource_NativeOnContentChangedListener */

#ifndef _Included_com_atakmap_map_elevation_NativeElevationSource_NativeOnContentChangedListener
#define _Included_com_atakmap_map_elevation_NativeElevationSource_NativeOnContentChangedListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_elevation_NativeElevationSource_CallbackForwarder */

#ifndef _Included_com_atakmap_map_elevation_NativeElevationSource_CallbackForwarder
#define _Included_com_atakmap_map_elevation_NativeElevationSource_CallbackForwarder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
