/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_feature_NativeFeatureSetCursor */

#ifndef _Included_com_atakmap_map_layer_feature_NativeFeatureSetCursor
#define _Included_com_atakmap_map_layer_feature_NativeFeatureSetCursor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureSetCursor
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureSetCursor_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureSetCursor
 * Method:    getId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureSetCursor_getId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureSetCursor
 * Method:    getType
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureSetCursor_getType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureSetCursor
 * Method:    getProvider
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureSetCursor_getProvider
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureSetCursor
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureSetCursor_getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureSetCursor
 * Method:    getMinResolution
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureSetCursor_getMinResolution
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureSetCursor
 * Method:    getMaxResolution
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureSetCursor_getMaxResolution
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureSetCursor
 * Method:    getVersion
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureSetCursor_getVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureSetCursor
 * Method:    moveToNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureSetCursor_moveToNext
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
