/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_feature_NativeFeatureCursor */

#ifndef _Included_com_atakmap_map_layer_feature_NativeFeatureCursor
#define _Included_com_atakmap_map_layer_feature_NativeFeatureCursor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureCursor
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureCursor_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureCursor
 * Method:    getRawGeometry
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureCursor_getRawGeometry
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureCursor
 * Method:    getGeomCoding
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureCursor_getGeomCoding
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureCursor
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureCursor_getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureCursor
 * Method:    getStyleCoding
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureCursor_getStyleCoding
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureCursor
 * Method:    getRawStyle
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureCursor_getRawStyle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureCursor
 * Method:    getAttributes
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureCursor_getAttributes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureCursor
 * Method:    getId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureCursor_getId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureCursor
 * Method:    getVersion
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureCursor_getVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureCursor
 * Method:    getFsid
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureCursor_getFsid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureCursor
 * Method:    moveToNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureCursor_moveToNext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureCursor
 * Method:    getTimestamp
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureCursor_getTimestamp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureCursor
 * Method:    getAltitudeMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureCursor_getAltitudeMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_NativeFeatureCursor
 * Method:    getExtrude
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_layer_feature_NativeFeatureCursor_getExtrude
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
