/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2 */

#ifndef _Included_com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2
#define _Included_com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2
 * Method:    create
 * Signature: (Ljava/lang/String;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2_create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2
 * Method:    asBase
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2_asBase
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2
 * Method:    contains
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2_contains
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2
 * Method:    getFile
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2_getFile
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2
 * Method:    add
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2_add__JLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2
 * Method:    add
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2_add__JLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2
 * Method:    remove
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2_remove
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2
 * Method:    update
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2_update
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2
 * Method:    queryFiles
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2_queryFiles
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2
 * Method:    refresh
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2_refresh
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2
 * Method:    queryFeatureSets
 * Signature: (JLjava/lang/String;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2_queryFeatureSets
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2_FeatureSetCursorAdapter */

#ifndef _Included_com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2_FeatureSetCursorAdapter
#define _Included_com_atakmap_map_layer_feature_PersistentDataSourceFeatureDataStore2_FeatureSetCursorAdapter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
