/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_raster_PersistentRasterDataStore */

#ifndef _Included_com_atakmap_map_layer_raster_PersistentRasterDataStore
#define _Included_com_atakmap_map_layer_raster_PersistentRasterDataStore
#ifdef __cplusplus
extern "C" {
#endif
#undef com_atakmap_map_layer_raster_PersistentRasterDataStore_RESOLVE_COLLECTION_COVERAGES
#define com_atakmap_map_layer_raster_PersistentRasterDataStore_RESOLVE_COLLECTION_COVERAGES 1L
#undef com_atakmap_map_layer_raster_PersistentRasterDataStore_LARGE_DATASET_RECURSE_LIMIT
#define com_atakmap_map_layer_raster_PersistentRasterDataStore_LARGE_DATASET_RECURSE_LIMIT 5000LL
#undef com_atakmap_map_layer_raster_PersistentRasterDataStore_CURRENCY_VERSION
#define com_atakmap_map_layer_raster_PersistentRasterDataStore_CURRENCY_VERSION 3L
/*
 * Class:     com_atakmap_map_layer_raster_PersistentRasterDataStore
 * Method:    getFileTreeData
 * Signature: (Ljava/lang/String;JJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_raster_PersistentRasterDataStore_getFileTreeData
  (JNIEnv *, jclass, jstring, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_raster_PersistentRasterDataStore_BackgroundCoverageResolver */

#ifndef _Included_com_atakmap_map_layer_raster_PersistentRasterDataStore_BackgroundCoverageResolver
#define _Included_com_atakmap_map_layer_raster_PersistentRasterDataStore_BackgroundCoverageResolver
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_raster_PersistentRasterDataStore_QueryInfoSpec */

#ifndef _Included_com_atakmap_map_layer_raster_PersistentRasterDataStore_QueryInfoSpec
#define _Included_com_atakmap_map_layer_raster_PersistentRasterDataStore_QueryInfoSpec
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_raster_PersistentRasterDataStore_SelectionBuilder */

#ifndef _Included_com_atakmap_map_layer_raster_PersistentRasterDataStore_SelectionBuilder
#define _Included_com_atakmap_map_layer_raster_PersistentRasterDataStore_SelectionBuilder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_raster_PersistentRasterDataStore_FileCursorImpl */

#ifndef _Included_com_atakmap_map_layer_raster_PersistentRasterDataStore_FileCursorImpl
#define _Included_com_atakmap_map_layer_raster_PersistentRasterDataStore_FileCursorImpl
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_raster_PersistentRasterDataStore_LayerCursorImpl */

#ifndef _Included_com_atakmap_map_layer_raster_PersistentRasterDataStore_LayerCursorImpl
#define _Included_com_atakmap_map_layer_raster_PersistentRasterDataStore_LayerCursorImpl
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_raster_PersistentRasterDataStore_GenerateCurrency */

#ifndef _Included_com_atakmap_map_layer_raster_PersistentRasterDataStore_GenerateCurrency
#define _Included_com_atakmap_map_layer_raster_PersistentRasterDataStore_GenerateCurrency
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_raster_PersistentRasterDataStore_ValidateCurrency */

#ifndef _Included_com_atakmap_map_layer_raster_PersistentRasterDataStore_ValidateCurrency
#define _Included_com_atakmap_map_layer_raster_PersistentRasterDataStore_ValidateCurrency
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
