/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_interop_Pointer */

#ifndef _Included_com_atakmap_interop_Pointer
#define _Included_com_atakmap_interop_Pointer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_atakmap_interop_Pointer_RAW
#define com_atakmap_interop_Pointer_RAW 0L
#undef com_atakmap_interop_Pointer_SHARED
#define com_atakmap_interop_Pointer_SHARED 1L
#undef com_atakmap_interop_Pointer_UNIQUE
#define com_atakmap_interop_Pointer_UNIQUE 2L
#undef com_atakmap_interop_Pointer_REFERENCE
#define com_atakmap_interop_Pointer_REFERENCE 3L
#ifdef __cplusplus
}
#endif
#endif
