/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_projection_ProjectionFactory */

#ifndef _Included_com_atakmap_map_projection_ProjectionFactory
#define _Included_com_atakmap_map_projection_ProjectionFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_projection_ProjectionFactory
 * Method:    setPreferLibrarySpi
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_projection_ProjectionFactory_setPreferLibrarySpi
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_atakmap_map_projection_ProjectionFactory
 * Method:    registerSpiImpl
 * Signature: (Lcom/atakmap/map/projection/ProjectionSpi;I)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_projection_ProjectionFactory_registerSpiImpl
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_atakmap_map_projection_ProjectionFactory
 * Method:    unregisterSpiImpl
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_projection_ProjectionFactory_unregisterSpiImpl
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_projection_ProjectionFactory
 * Method:    getProjectionImpl
 * Signature: (I)Lcom/atakmap/map/projection/Projection;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_projection_ProjectionFactory_getProjectionImpl
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_projection_ProjectionFactory_LibraryProjectionSpi */

#ifndef _Included_com_atakmap_map_projection_ProjectionFactory_LibraryProjectionSpi
#define _Included_com_atakmap_map_projection_ProjectionFactory_LibraryProjectionSpi
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
