/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_RenderContextInterop */

#ifndef _Included_com_atakmap_map_RenderContextInterop
#define _Included_com_atakmap_map_RenderContextInterop
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_RenderContextInterop
 * Method:    wrap
 * Signature: (Lcom/atakmap/map/RenderContext;)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_RenderContextInterop_wrap
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_RenderContextInterop
 * Method:    hasObject
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_RenderContextInterop_hasObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_RenderContextInterop
 * Method:    getObject
 * Signature: (J)Lcom/atakmap/map/RenderContext;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_RenderContextInterop_getObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_RenderContextInterop
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_RenderContextInterop_destruct
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
