/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_opengl_Skirt */

#ifndef _Included_com_atakmap_opengl_Skirt
#define _Included_com_atakmap_opengl_Skirt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_opengl_Skirt
 * Method:    create
 * Signature: (IIIJIIIJIIJIF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_opengl_Skirt_create
  (JNIEnv *, jclass, jint, jint, jint, jlong, jint, jint, jint, jlong, jint, jint, jlong, jint, jfloat);

/*
 * Class:     com_atakmap_opengl_Skirt
 * Method:    getNumOutputVertices
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_opengl_Skirt_getNumOutputVertices
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_atakmap_opengl_Skirt
 * Method:    getNumOutputIndices
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_opengl_Skirt_getNumOutputIndices
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
