/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_database_impl_StatementImpl */

#ifndef _Included_com_atakmap_database_impl_StatementImpl
#define _Included_com_atakmap_database_impl_StatementImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_database_impl_StatementImpl
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_database_impl_StatementImpl_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_database_impl_StatementImpl
 * Method:    execute
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_database_impl_StatementImpl_execute
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_database_impl_StatementImpl
 * Method:    bindBinary
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_database_impl_StatementImpl_bindBinary
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     com_atakmap_database_impl_StatementImpl
 * Method:    bindInt
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_database_impl_StatementImpl_bindInt
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_atakmap_database_impl_StatementImpl
 * Method:    bindLong
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_database_impl_StatementImpl_bindLong
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     com_atakmap_database_impl_StatementImpl
 * Method:    bindDouble
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_database_impl_StatementImpl_bindDouble
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     com_atakmap_database_impl_StatementImpl
 * Method:    bindString
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_database_impl_StatementImpl_bindString
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     com_atakmap_database_impl_StatementImpl
 * Method:    bindNull
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_database_impl_StatementImpl_bindNull
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_atakmap_database_impl_StatementImpl
 * Method:    clearBindings
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_database_impl_StatementImpl_clearBindings
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
