/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_feature_style_Style */

#ifndef _Included_com_atakmap_map_layer_feature_style_Style
#define _Included_com_atakmap_map_layer_feature_style_Style
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getTESC_BasicStrokeStyle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getTESC_1BasicStrokeStyle
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getTESC_BasicFillStyle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getTESC_1BasicFillStyle
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getTESC_BasicPointStyle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getTESC_1BasicPointStyle
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getTESC_IconPointStyle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getTESC_1IconPointStyle
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getTESC_LabelPointStyle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getTESC_1LabelPointStyle
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getTESC_CompositeStyle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getTESC_1CompositeStyle
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getTESC_PatternStrokeStyle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getTESC_1PatternStrokeStyle
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    destruct
 * Signature: (Lcom/atakmap/interop/Pointer;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_layer_feature_style_Style_destruct
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    clone
 * Signature: (J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_style_Style_clone
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getClass
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getClass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    BasicFillStyle_create
 * Signature: (I)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_style_Style_BasicFillStyle_1create
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    BasicFillStyle_getColor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_BasicFillStyle_1getColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    BasicStrokeStyle_create
 * Signature: (IF)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_style_Style_BasicStrokeStyle_1create
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    BasicStrokeStyle_getColor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_BasicStrokeStyle_1getColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    BasicStrokeStyle_getStrokeWidth
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_map_layer_feature_style_Style_BasicStrokeStyle_1getStrokeWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    BasicPointStyle_create
 * Signature: (IF)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_style_Style_BasicPointStyle_1create
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    BasicPointStyle_getColor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_BasicPointStyle_1getColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    BasicPointStyle_getSize
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_map_layer_feature_style_Style_BasicPointStyle_1getSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    IconPointStyle_create
 * Signature: (ILjava/lang/String;FFIIFZ)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_style_Style_IconPointStyle_1create__ILjava_lang_String_2FFIIFZ
  (JNIEnv *, jclass, jint, jstring, jfloat, jfloat, jint, jint, jfloat, jboolean);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    IconPointStyle_create
 * Signature: (ILjava/lang/String;FIIFZ)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_style_Style_IconPointStyle_1create__ILjava_lang_String_2FIIFZ
  (JNIEnv *, jclass, jint, jstring, jfloat, jint, jint, jfloat, jboolean);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    IconPointStyle_getColor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_IconPointStyle_1getColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    IconPointStyle_getUri
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_layer_feature_style_Style_IconPointStyle_1getUri
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    IconPointStyle_getWidth
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_map_layer_feature_style_Style_IconPointStyle_1getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    IconPointStyle_getHeight
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_map_layer_feature_style_Style_IconPointStyle_1getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    IconPointStyle_getHorizontalAlignment
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_IconPointStyle_1getHorizontalAlignment
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    IconPointStyle_getVerticalAlignment
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_IconPointStyle_1getVerticalAlignment
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    IconPointStyle_getScaling
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_map_layer_feature_style_Style_IconPointStyle_1getScaling
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    IconPointStyle_getRotation
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_map_layer_feature_style_Style_IconPointStyle_1getRotation
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    IconPointStyle_isRotationAbsolute
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_style_Style_IconPointStyle_1isRotationAbsolute
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getIconPointStyle_HorizontalAlignment_LEFT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getIconPointStyle_1HorizontalAlignment_1LEFT
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getIconPointStyle_HorizontalAlignment_H_CENTER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getIconPointStyle_1HorizontalAlignment_1H_1CENTER
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getIconPointStyle_HorizontalAlignment_RIGHT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getIconPointStyle_1HorizontalAlignment_1RIGHT
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getIconPointStyle_VerticalAlignment_ABOVE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getIconPointStyle_1VerticalAlignment_1ABOVE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getIconPointStyle_VerticalAlignment_V_CENTER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getIconPointStyle_1VerticalAlignment_1V_1CENTER
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getIconPointStyle_VerticalAlignment_BELOW
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getIconPointStyle_1VerticalAlignment_1BELOW
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    LabelPointStyle_create
 * Signature: (Ljava/lang/String;IIIFIIFZDF)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_style_Style_LabelPointStyle_1create
  (JNIEnv *, jclass, jstring, jint, jint, jint, jfloat, jint, jint, jfloat, jboolean, jdouble, jfloat);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    LabelPointStyle_getText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_map_layer_feature_style_Style_LabelPointStyle_1getText
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    LabelPointStyle_getTextColor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_LabelPointStyle_1getTextColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    LabelPointStyle_getBackgroundColor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_LabelPointStyle_1getBackgroundColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    LabelPointStyle_getScrollMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_LabelPointStyle_1getScrollMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    LabelPointStyle_getTextSize
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_map_layer_feature_style_Style_LabelPointStyle_1getTextSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    LabelPointStyle_getHorizontalAlignment
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_LabelPointStyle_1getHorizontalAlignment
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    LabelPointStyle_getVerticalAlignment
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_LabelPointStyle_1getVerticalAlignment
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    LabelPointStyle_getRotation
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_map_layer_feature_style_Style_LabelPointStyle_1getRotation
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    LabelPointStyle_isRotationAbsolute
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_feature_style_Style_LabelPointStyle_1isRotationAbsolute
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    LabelPointStyle_getLabelMinRenderResolution
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_map_layer_feature_style_Style_LabelPointStyle_1getLabelMinRenderResolution
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    LabelPointStyle_getLabelScale
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_map_layer_feature_style_Style_LabelPointStyle_1getLabelScale
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getLabelPointStyle_HorizontalAlignment_LEFT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getLabelPointStyle_1HorizontalAlignment_1LEFT
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getLabelPointStyle_HorizontalAlignment_H_CENTER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getLabelPointStyle_1HorizontalAlignment_1H_1CENTER
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getLabelPointStyle_HorizontalAlignment_RIGHT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getLabelPointStyle_1HorizontalAlignment_1RIGHT
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getLabelPointStyle_VerticalAlignment_ABOVE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getLabelPointStyle_1VerticalAlignment_1ABOVE
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getLabelPointStyle_VerticalAlignment_V_CENTER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getLabelPointStyle_1VerticalAlignment_1V_1CENTER
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getLabelPointStyle_VerticalAlignment_BELOW
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getLabelPointStyle_1VerticalAlignment_1BELOW
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getLabelPointStyle_ScrollMode_DEFAULT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getLabelPointStyle_1ScrollMode_1DEFAULT
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getLabelPointStyle_ScrollMode_ON
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getLabelPointStyle_1ScrollMode_1ON
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    getLabelPointStyle_ScrollMode_OFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_getLabelPointStyle_1ScrollMode_1OFF
  (JNIEnv *, jclass);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    CompositeStyle_create
 * Signature: ([J)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_style_Style_CompositeStyle_1create
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    CompositeStyle_getNumStyles
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_CompositeStyle_1getNumStyles
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    CompositeStyle_getStyle
 * Signature: (JI)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_style_Style_CompositeStyle_1getStyle
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    PatternStrokeStyle_create
 * Signature: (ISIF)Lcom/atakmap/interop/Pointer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_map_layer_feature_style_Style_PatternStrokeStyle_1create
  (JNIEnv *, jclass, jint, jshort, jint, jfloat);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    PatternStrokeStyle_getPattern
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_atakmap_map_layer_feature_style_Style_PatternStrokeStyle_1getPattern
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    PatternStrokeStyle_getFactor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_PatternStrokeStyle_1getFactor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    PatternStrokeStyle_getColor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_feature_style_Style_PatternStrokeStyle_1getColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_feature_style_Style
 * Method:    PatternStrokeStyle_getStrokeWidth
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_map_layer_feature_style_Style_PatternStrokeStyle_1getStrokeWidth
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_feature_style_Style_StyleClasses */

#ifndef _Included_com_atakmap_map_layer_feature_style_Style_StyleClasses
#define _Included_com_atakmap_map_layer_feature_style_Style_StyleClasses
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
