/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_opengl_Tessellate */

#ifndef _Included_com_atakmap_opengl_Tessellate
#define _Included_com_atakmap_opengl_Tessellate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_opengl_Tessellate
 * Method:    linestring
 * Signature: ([DIIDZ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_atakmap_opengl_Tessellate_linestring___3DIIDZ
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jdouble, jboolean);

/*
 * Class:     com_atakmap_opengl_Tessellate
 * Method:    linestring
 * Signature: ([FIIDZ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_atakmap_opengl_Tessellate_linestring___3FIIDZ
  (JNIEnv *, jclass, jfloatArray, jint, jint, jdouble, jboolean);

/*
 * Class:     com_atakmap_opengl_Tessellate
 * Method:    linestring
 * Signature: (ILjava/nio/Buffer;IIIDZ)Ljava/nio/Buffer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_opengl_Tessellate_linestring__ILjava_nio_Buffer_2IIIDZ
  (JNIEnv *, jclass, jint, jobject, jint, jint, jint, jdouble, jboolean);

/*
 * Class:     com_atakmap_opengl_Tessellate
 * Method:    polygonImpl
 * Signature: (Ljava/nio/DoubleBuffer;IIIDZ)Ljava/nio/Buffer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_opengl_Tessellate_polygonImpl__Ljava_nio_DoubleBuffer_2IIIDZ
  (JNIEnv *, jclass, jobject, jint, jint, jint, jdouble, jboolean);

/*
 * Class:     com_atakmap_opengl_Tessellate
 * Method:    polygonImpl
 * Signature: (Ljava/nio/DoubleBuffer;II[I[IIDZ)Ljava/nio/Buffer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_opengl_Tessellate_polygonImpl__Ljava_nio_DoubleBuffer_2II_3I_3IIDZ
  (JNIEnv *, jclass, jobject, jint, jint, jintArray, jintArray, jint, jdouble, jboolean);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_opengl_Tessellate_Mode */

#ifndef _Included_com_atakmap_opengl_Tessellate_Mode
#define _Included_com_atakmap_opengl_Tessellate_Mode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
