/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_lang_Unsafe */

#ifndef _Included_com_atakmap_lang_Unsafe
#define _Included_com_atakmap_lang_Unsafe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    allocate
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_lang_Unsafe_allocate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    newDirectBuffer
 * Signature: (JI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_atakmap_lang_Unsafe_newDirectBuffer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    memset
 * Signature: (JBI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_memset
  (JNIEnv *, jclass, jlong, jbyte, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    memcpy
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_memcpy__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    memmove
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_memmove
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    memcpy
 * Signature: (Ljava/nio/ByteBuffer;IJI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_memcpy__Ljava_nio_ByteBuffer_2IJI
  (JNIEnv *, jclass, jobject, jint, jlong, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    memcpy
 * Signature: (JLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_memcpy__JLjava_nio_ByteBuffer_2II
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    getBufferPointer
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_lang_Unsafe_getBufferPointer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setByteNio
 * Signature: (Ljava/nio/Buffer;IB)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setByteNio
  (JNIEnv *, jclass, jobject, jint, jbyte);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setBytesNio2
 * Signature: (Ljava/nio/Buffer;IBB)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setBytesNio2
  (JNIEnv *, jclass, jobject, jint, jbyte, jbyte);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setBytesNio3
 * Signature: (Ljava/nio/Buffer;IBBB)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setBytesNio3
  (JNIEnv *, jclass, jobject, jint, jbyte, jbyte, jbyte);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setBytesNio4
 * Signature: (Ljava/nio/Buffer;IBBBB)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setBytesNio4
  (JNIEnv *, jclass, jobject, jint, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setBytesNioArray
 * Signature: (Ljava/nio/Buffer;I[BI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setBytesNioArray
  (JNIEnv *, jclass, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setBytesNioArrayRegion
 * Signature: (Ljava/nio/Buffer;I[BII)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setBytesNioArrayRegion
  (JNIEnv *, jclass, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setShortNio
 * Signature: (Ljava/nio/Buffer;IS)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setShortNio
  (JNIEnv *, jclass, jobject, jint, jshort);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setShortsNio2
 * Signature: (Ljava/nio/Buffer;ISS)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setShortsNio2
  (JNIEnv *, jclass, jobject, jint, jshort, jshort);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setShortsNio3
 * Signature: (Ljava/nio/Buffer;ISSS)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setShortsNio3
  (JNIEnv *, jclass, jobject, jint, jshort, jshort, jshort);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setShortsNio4
 * Signature: (Ljava/nio/Buffer;ISSSS)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setShortsNio4
  (JNIEnv *, jclass, jobject, jint, jshort, jshort, jshort, jshort);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setShortsNioArray
 * Signature: (Ljava/nio/Buffer;I[SI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setShortsNioArray
  (JNIEnv *, jclass, jobject, jint, jshortArray, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setShortsNioArrayRegion
 * Signature: (Ljava/nio/Buffer;I[SII)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setShortsNioArrayRegion
  (JNIEnv *, jclass, jobject, jint, jshortArray, jint, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setIntNio
 * Signature: (Ljava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setIntNio
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setIntsNio2
 * Signature: (Ljava/nio/Buffer;III)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setIntsNio2
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setIntsNio3
 * Signature: (Ljava/nio/Buffer;IIII)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setIntsNio3
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setIntsNio4
 * Signature: (Ljava/nio/Buffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setIntsNio4
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setIntsNioArray
 * Signature: (Ljava/nio/Buffer;I[II)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setIntsNioArray
  (JNIEnv *, jclass, jobject, jint, jintArray, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setIntsNioArrayRegion
 * Signature: (Ljava/nio/Buffer;I[III)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setIntsNioArrayRegion
  (JNIEnv *, jclass, jobject, jint, jintArray, jint, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setLongNio
 * Signature: (Ljava/nio/Buffer;IJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setLongNio
  (JNIEnv *, jclass, jobject, jint, jlong);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setLongsNio2
 * Signature: (Ljava/nio/Buffer;IJJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setLongsNio2
  (JNIEnv *, jclass, jobject, jint, jlong, jlong);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setLongsNio3
 * Signature: (Ljava/nio/Buffer;IJJJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setLongsNio3
  (JNIEnv *, jclass, jobject, jint, jlong, jlong, jlong);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setLongsNio4
 * Signature: (Ljava/nio/Buffer;IJJJJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setLongsNio4
  (JNIEnv *, jclass, jobject, jint, jlong, jlong, jlong, jlong);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setLongsNioArray
 * Signature: (Ljava/nio/Buffer;I[JI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setLongsNioArray
  (JNIEnv *, jclass, jobject, jint, jlongArray, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setLongsNioArrayRegion
 * Signature: (Ljava/nio/Buffer;I[JII)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setLongsNioArrayRegion
  (JNIEnv *, jclass, jobject, jint, jlongArray, jint, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setFloatNio
 * Signature: (Ljava/nio/Buffer;IF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setFloatNio
  (JNIEnv *, jclass, jobject, jint, jfloat);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setFloatsNio2
 * Signature: (Ljava/nio/Buffer;IFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setFloatsNio2
  (JNIEnv *, jclass, jobject, jint, jfloat, jfloat);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setFloatsNio3
 * Signature: (Ljava/nio/Buffer;IFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setFloatsNio3
  (JNIEnv *, jclass, jobject, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setFloatsNio4
 * Signature: (Ljava/nio/Buffer;IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setFloatsNio4
  (JNIEnv *, jclass, jobject, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setFloatsNioArray
 * Signature: (Ljava/nio/Buffer;I[FI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setFloatsNioArray
  (JNIEnv *, jclass, jobject, jint, jfloatArray, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setFloatsNioArrayRegion
 * Signature: (Ljava/nio/Buffer;I[FII)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setFloatsNioArrayRegion
  (JNIEnv *, jclass, jobject, jint, jfloatArray, jint, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setDoubleNio
 * Signature: (Ljava/nio/Buffer;ID)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setDoubleNio
  (JNIEnv *, jclass, jobject, jint, jdouble);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setDoublesNio2
 * Signature: (Ljava/nio/Buffer;IDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setDoublesNio2
  (JNIEnv *, jclass, jobject, jint, jdouble, jdouble);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setDoublesNio3
 * Signature: (Ljava/nio/Buffer;IDDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setDoublesNio3
  (JNIEnv *, jclass, jobject, jint, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setDoublesNio4
 * Signature: (Ljava/nio/Buffer;IDDDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setDoublesNio4
  (JNIEnv *, jclass, jobject, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setDoublesNioArray
 * Signature: (Ljava/nio/Buffer;I[DI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setDoublesNioArray
  (JNIEnv *, jclass, jobject, jint, jdoubleArray, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setDoublesNioArrayRegion
 * Signature: (Ljava/nio/Buffer;I[DII)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setDoublesNioArrayRegion
  (JNIEnv *, jclass, jobject, jint, jdoubleArray, jint, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    getByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_com_atakmap_lang_Unsafe_getByte
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    getShort
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_atakmap_lang_Unsafe_getShort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    getInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_lang_Unsafe_getInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    getLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_atakmap_lang_Unsafe_getLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    getFloat
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_atakmap_lang_Unsafe_getFloat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    getDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_atakmap_lang_Unsafe_getDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setByte
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setByte
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setBytes
 * Signature: (JBB)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setBytes__JBB
  (JNIEnv *, jclass, jlong, jbyte, jbyte);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setBytes
 * Signature: (JBBB)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setBytes__JBBB
  (JNIEnv *, jclass, jlong, jbyte, jbyte, jbyte);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setBytes
 * Signature: (JBBBB)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setBytes__JBBBB
  (JNIEnv *, jclass, jlong, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setShort
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setShort
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setShorts
 * Signature: (JSS)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setShorts__JSS
  (JNIEnv *, jclass, jlong, jshort, jshort);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setShorts
 * Signature: (JSSS)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setShorts__JSSS
  (JNIEnv *, jclass, jlong, jshort, jshort, jshort);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setShorts
 * Signature: (JSSSS)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setShorts__JSSSS
  (JNIEnv *, jclass, jlong, jshort, jshort, jshort, jshort);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setInt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setInt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setInts
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setInts__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setInts
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setInts__JIII
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setInts
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setInts__JIIII
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setLong
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setLong
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setLongs
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setLongs__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setLongs
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setLongs__JJJJ
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setLongs
 * Signature: (JJJJJ)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setLongs__JJJJJ
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setFloat
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setFloat
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setFloats
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setFloats__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setFloats
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setFloats__JFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setFloats
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setFloats__JFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setDouble
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setDouble
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setDoubles
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setDoubles__JDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setDoubles
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setDoubles__JDDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     com_atakmap_lang_Unsafe
 * Method:    setDoubles
 * Signature: (JDDDD)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_lang_Unsafe_setDoubles__JDDDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_lang_Unsafe_DirectByteBuffer18 */

#ifndef _Included_com_atakmap_lang_Unsafe_DirectByteBuffer18
#define _Included_com_atakmap_lang_Unsafe_DirectByteBuffer18
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_lang_Unsafe_DirectByteBuffer23 */

#ifndef _Included_com_atakmap_lang_Unsafe_DirectByteBuffer23
#define _Included_com_atakmap_lang_Unsafe_DirectByteBuffer23
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_lang_Unsafe_DirectByteBufferApi */

#ifndef _Included_com_atakmap_lang_Unsafe_DirectByteBufferApi
#define _Included_com_atakmap_lang_Unsafe_DirectByteBufferApi
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
