/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_layer_model_VertexDataLayout */

#ifndef _Included_com_atakmap_map_layer_model_VertexDataLayout
#define _Included_com_atakmap_map_layer_model_VertexDataLayout
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getAttributes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getAttributes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getPositionDataType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getPositionDataType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getPositionOffset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getPositionOffset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getPositionStride
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getPositionStride
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord0DataType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord0DataType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord0Offset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord0Offset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord0Stride
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord0Stride
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord1DataType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord1DataType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord1Offset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord1Offset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord1Stride
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord1Stride
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord2DataType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord2DataType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord2Offset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord2Offset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord2Stride
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord2Stride
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord3DataType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord3DataType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord3Offset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord3Offset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord3Stride
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord3Stride
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord4DataType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord4DataType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord4Offset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord4Offset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord4Stride
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord4Stride
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord5DataType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord5DataType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord5Offset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord5Offset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord5Stride
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord5Stride
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord6DataType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord6DataType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord6Offset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord6Offset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord6Stride
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord6Stride
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord7DataType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord7DataType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord7Offset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord7Offset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getTexCoord7Stride
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getTexCoord7Stride
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getNormalDataType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getNormalDataType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getNormalOffset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getNormalOffset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getNormalStride
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getNormalStride
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getColorDataType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getColorDataType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getColorOffset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getColorOffset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getColorStride
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getColorStride
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    getInterleaved
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_getInterleaved
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_atakmap_map_layer_model_VertexDataLayout
 * Method:    requiredInterleavedDataSize
 * Signature: (IIIIIIIIIIIIIZI)I
 */
JNIEXPORT jint JNICALL Java_com_atakmap_map_layer_model_VertexDataLayout_requiredInterleavedDataSize
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_atakmap_map_layer_model_VertexDataLayout_Array */

#ifndef _Included_com_atakmap_map_layer_model_VertexDataLayout_Array
#define _Included_com_atakmap_map_layer_model_VertexDataLayout_Array
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
