/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_map_gdal_VSIJFileFilesystemHandler */

#ifndef _Included_com_atakmap_map_gdal_VSIJFileFilesystemHandler
#define _Included_com_atakmap_map_gdal_VSIJFileFilesystemHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_map_gdal_VSIJFileFilesystemHandler
 * Method:    installFilesystemHandler
 * Signature: (Ljava/lang/String;Lcom/atakmap/map/gdal/VSIJFileFilesystemHandler;)V
 */
JNIEXPORT void JNICALL Java_com_atakmap_map_gdal_VSIJFileFilesystemHandler_installFilesystemHandler
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
